//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bombardier.PTU.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bombardier.PTU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BombardierLogo {
            get {
                object obj = ResourceManager.GetObject("BombardierLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bookmark {
            get {
                object obj = ResourceManager.GetObject("Bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CarNumber {
            get {
                object obj = ResourceManager.GetObject("CarNumber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMPort {
            get {
                object obj = ResourceManager.GetObject("COMPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMPort1 {
            get {
                object obj = ResourceManager.GetObject("COMPort1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Configuration {
            get {
                object obj = ResourceManager.GetObject("Configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataStream {
            get {
                object obj = ResourceManager.GetObject("DataStream", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataStreamSimulated {
            get {
                object obj = ResourceManager.GetObject("DataStreamSimulated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the browser specified in the user settings..
        /// </summary>
        internal static string EMBrowserStartFailed {
            get {
                return ResourceManager.GetString("EMBrowserStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the car identifier..
        /// </summary>
        internal static string EMCarIDSetFailed {
            get {
                return ResourceManager.GetString("EMCarIDSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the time and date..
        /// </summary>
        internal static string EMTimeDateGetFailed {
            get {
                return ResourceManager.GetString("EMTimeDateGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the time and date..
        /// </summary>
        internal static string EMTimeDateSetFailed {
            get {
                return ResourceManager.GetString("EMTimeDateSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eventlog {
            get {
                object obj = ResourceManager.GetObject("Eventlog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Dictionary Files.
        /// </summary>
        internal static string FileDialogOpenFilterDataDictionary {
            get {
                return ResourceManager.GetString("FileDialogOpenFilterDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data Dictionary.
        /// </summary>
        internal static string FileDialogOpenTitleDataDictionary {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Web Browser.
        /// </summary>
        internal static string FileDialogOpenTitleWebBrowser {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadConfiguration.bat.
        /// </summary>
        internal static string FilenameConfigDownload {
            get {
                return ResourceManager.GetString("FilenameConfigDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.xml.
        /// </summary>
        internal static string FilenameDefaultDataDictionary {
            get {
                return ResourceManager.GetString("FilenameDefaultDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Equipment - Release Notes.pdf.
        /// </summary>
        internal static string FilenameReleaseNotesPTE {
            get {
                return ResourceManager.GetString("FilenameReleaseNotesPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Unit - Release Notes.pdf.
        /// </summary>
        internal static string FilenameReleaseNotesPTU {
            get {
                return ResourceManager.GetString("FilenameReleaseNotesPTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Equipment - Software User Manual.pdf.
        /// </summary>
        internal static string FilenameSoftwareUserManualPTE {
            get {
                return ResourceManager.GetString("FilenameSoftwareUserManualPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Unit - Software User Manual.pdf.
        /// </summary>
        internal static string FilenameSoftwareUserManualPTU {
            get {
                return ResourceManager.GetString("FilenameSoftwareUserManualPTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Font {
            get {
                object obj = ResourceManager.GetObject("Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fSEARCH_00 {
            get {
                object obj = ResourceManager.GetObject("fSEARCH_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Function {
            get {
                object obj = ResourceManager.GetObject("Function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2-Disconnect Logic.
        /// </summary>
        internal static string FunctionKeyTextDisconnectLogic {
            get {
                return ResourceManager.GetString("FunctionKeyTextDisconnectLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3-Offline.
        /// </summary>
        internal static string FunctionKeyTextOffline {
            get {
                return ResourceManager.GetString("FunctionKeyTextOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2-Online.
        /// </summary>
        internal static string FunctionKeyTextOnline {
            get {
                return ResourceManager.GetString("FunctionKeyTextOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2-Select Target Logic.
        /// </summary>
        internal static string FunctionKeyTextSelectLogic {
            get {
                return ResourceManager.GetString("FunctionKeyTextSelectLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3-Exit Simulation.
        /// </summary>
        internal static string FunctionKeyTextSimulationExit {
            get {
                return ResourceManager.GetString("FunctionKeyTextSimulationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3-Logic Simulation.
        /// </summary>
        internal static string FunctionKeyTextSimulationStart {
            get {
                return ResourceManager.GetString("FunctionKeyTextSimulationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Disconnect the Vehicle Control Unit].
        /// </summary>
        internal static string FunctionKeyToolTipTextDisconnectLogic {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipTextDisconnectLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Display Screens without Connecting to the Vehicle Control Unit].
        /// </summary>
        internal static string FunctionKeyToolTipTextOffline {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipTextOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Connect to the Vehicle Control Unit].
        /// </summary>
        internal static string FunctionKeyToolTipTextOnline {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipTextOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Connect to the Vehicle Control Unit].
        /// </summary>
        internal static string FunctionKeyToolTipTextSelectLogic {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipTextSelectLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Exit the Vehicle Control Unit Simulation].
        /// </summary>
        internal static string FunctionKeyToolTipTextSimulationExit {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipTextSimulationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Start the Vehicle Control Unit Simulation].
        /// </summary>
        internal static string FunctionKeyToolTipTextSimulationStart {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipTextSimulationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HotPlug {
            get {
                object obj = ResourceManager.GetObject("HotPlug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Initialize {
            get {
                object obj = ResourceManager.GetObject("Initialize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keys {
            get {
                object obj = ResourceManager.GetObject("Keys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LabelModeDiagnostic {
            get {
                return ResourceManager.GetString("LabelModeDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string LabelModeOffline {
            get {
                return ResourceManager.GetString("LabelModeOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string LabelModeOnline {
            get {
                return ResourceManager.GetString("LabelModeOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Test.
        /// </summary>
        internal static string LabelModeSelfTest {
            get {
                return ResourceManager.GetString("LabelModeSelfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string LabelModeSetup {
            get {
                return ResourceManager.GetString("LabelModeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        internal static string LabelModeVCUSimulation {
            get {
                return ResourceManager.GetString("LabelModeVCUSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.bombardier.com.
        /// </summary>
        internal static string LabelWebAddress {
            get {
                return ResourceManager.GetString("LabelWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Present.
        /// </summary>
        internal static string LabelWibuBoxStatusNotPresent {
            get {
                return ResourceManager.GetString("LabelWibuBoxStatusNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string LabelWibuBoxStatusPresent {
            get {
                return ResourceManager.GetString("LabelWibuBoxStatusPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car No.:.
        /// </summary>
        internal static string LegendCarNumber {
            get {
                return ResourceManager.GetString("LegendCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (C) 2010 - 2015  Bombardier Transportation (Holdings) USA Inc..
        /// </summary>
        internal static string LegendCopyright {
            get {
                return ResourceManager.GetString("LegendCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log:.
        /// </summary>
        internal static string LegendLogStatus {
            get {
                return ResourceManager.GetString("LegendLogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LegendMode {
            get {
                return ResourceManager.GetString("LegendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 7/Vista/XP.
        /// </summary>
        internal static string LegendOS {
            get {
                return ResourceManager.GetString("LegendOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string LegendRights {
            get {
                return ResourceManager.GetString("LegendRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LegendSecurityLevel {
            get {
                return ResourceManager.GetString("LegendSecurityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LegendWibuBoxStatus {
            get {
                return ResourceManager.GetString("LegendWibuBoxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightMetallic {
            get {
                object obj = ResourceManager.GetObject("LightMetallic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.bombardier.com/en/transportation.html.
        /// </summary>
        internal static string LinkBombardier {
            get {
                return ResourceManager.GetString("LinkBombardier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MBCaptionError {
            get {
                return ResourceManager.GetString("MBCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MBCaptionInformation {
            get {
                return ResourceManager.GetString("MBCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MBCaptionWarning {
            get {
                return ResourceManager.GetString("MBCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default data dictionary, &apos;{0}&apos;, could not be found, please select a valid data dictionary..
        /// </summary>
        internal static string MBTConfigDefaultNotFound {
            get {
                return ResourceManager.GetString("MBTConfigDefaultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data dictionary, &apos;{0}&apos;, is invalid and cannot be read..
        /// </summary>
        internal static string MBTConfigInvalid {
            get {
                return ResourceManager.GetString("MBTConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project identifier associated with the current data dictionary is not applicable to this project, please contact the system administrator..
        /// </summary>
        internal static string MBTConfigProjectAsParameterMismatch {
            get {
                return ResourceManager.GetString("MBTConfigProjectAsParameterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified project data dictionary could not be found. An attempt will be made to load the default data dictionary, &apos;{0}&apos;, instead..
        /// </summary>
        internal static string MBTConfigProjectNotFound {
            get {
                return ResourceManager.GetString("MBTConfigProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the data dictionary..
        /// </summary>
        internal static string MBTConfigReadFailed {
            get {
                return ResourceManager.GetString("MBTConfigReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the system administrator or use the &apos;File/Open - Data Dictionary&apos; menu option to select another data dictionary..
        /// </summary>
        internal static string MBTConfigReselect {
            get {
                return ResourceManager.GetString("MBTConfigReselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PTU configuration has been updated. Please disconnect the Ethernet cable and reconnect the original RS-232 connection. Click &apos;OK&apos; when the PTU is reconnected to the propulsion system..
        /// </summary>
        internal static string MBTConfigVCUDownloadComplete {
            get {
                return ResourceManager.GetString("MBTConfigVCUDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download the PTU configuration from the propulsion system..
        /// </summary>
        internal static string MBTConfigVCUDownloadFailed {
            get {
                return ResourceManager.GetString("MBTConfigVCUDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file transfer is in progress. Please do not disconnect the Ethernet cable until the transfer is complete..
        /// </summary>
        internal static string MBTConfigVCUDownloadInProgress {
            get {
                return ResourceManager.GetString("MBTConfigVCUDownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to update the PTU configuration: {0}1. Please disconnect the RS-232 connection and move the PTU up to the cab area. {1}2. Using a M12 to RS-485 Ethernet cable, connect the PTU laptop port (RJ45) to the J4 port (M12) located in the ceiling cabinet directly above the doorway entrance to the cab and locker area. The J4 Ethernet port is located directly to the left of the HV Box RS-232 serial port in this cabinet.{2}3. Once the connection is established, please click &apos;OK&apos; to begin updating the PTU conf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MBTConfigVCUDownloadStart {
            get {
                return ResourceManager.GetString("MBTConfigVCUDownloadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PTU configuration file associated with the propulsion system software could not be found in the default sub-directory, do you want to select a file manually?.
        /// </summary>
        internal static string MBTConfigVCUMatchNotFoundManualSelection {
            get {
                return ResourceManager.GetString("MBTConfigVCUMatchNotFoundManualSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PTU configuration file associated with the propulsion system software still cannot be found in the default sub-directory. Please try again.&quot;.
        /// </summary>
        internal static string MBTConfigVCUMatchNotFoundTryAgain {
            get {
                return ResourceManager.GetString("MBTConfigVCUMatchNotFoundTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project identifier of the PTU configuration does not match that of the propulsion system software. Would you like to update the PTU configuration now?.
        /// </summary>
        internal static string MBTConfigVCUMismatchProjectId {
            get {
                return ResourceManager.GetString("MBTConfigVCUMismatchProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version reference of the PTU configuration does not match that of the propulsion system software. Would you like to update the PTU configuration now?.
        /// </summary>
        internal static string MBTConfigVCUMismatchVersion {
            get {
                return ResourceManager.GetString("MBTConfigVCUMismatchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application data path specified in the configuration file is invalid; using the Windows default path..
        /// </summary>
        internal static string MBTDataDictionaryApplicationDataPathInvalid {
            get {
                return ResourceManager.GetString("MBTDataDictionaryApplicationDataPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the data dictionary..
        /// </summary>
        internal static string MBTDataDictionaryLoadFailed {
            get {
                return ResourceManager.GetString("MBTDataDictionaryLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data dictionary did not contain a valid project identifier, please contact the system administrator..
        /// </summary>
        internal static string MBTDataDictionaryProjectIdEmpty {
            get {
                return ResourceManager.GetString("MBTDataDictionaryProjectIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the date and time..
        /// </summary>
        internal static string MBTDateTimeGetFailed {
            get {
                return ResourceManager.GetString("MBTDateTimeGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the real time clock..
        /// </summary>
        internal static string MBTDateTimeSetFailed {
            get {
                return ResourceManager.GetString("MBTDateTimeSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The real time clock has been successfully updated..
        /// </summary>
        internal static string MBTDateTimeSetSuccess {
            get {
                return ResourceManager.GetString("MBTDateTimeSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic help file for the current project cannot be found..
        /// </summary>
        internal static string MBTDiagnosticHelpNotFound {
            get {
                return ResourceManager.GetString("MBTDiagnosticHelpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The help document cannot be found..
        /// </summary>
        internal static string MBTHelpFileNotFound {
            get {
                return ResourceManager.GetString("MBTHelpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The watch variables associated with the following old identifiers are present in the &apos;{0}&apos; workset file but cannot be found in the data dictionary: {1}..
        /// </summary>
        internal static string MBTInvalidWorkset {
            get {
                return ResourceManager.GetString("MBTInvalidWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No targets were found. Please select Retry to rescan all available ports..
        /// </summary>
        internal static string MBTLogicsNotFound {
            get {
                return ResourceManager.GetString("MBTLogicsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the mode of the chart recorder..
        /// </summary>
        internal static string MBTModifyChartRecorderModeFailed {
            get {
                return ResourceManager.GetString("MBTModifyChartRecorderModeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no passwords associated with the current security configuration..
        /// </summary>
        internal static string MBTNoPasswordsToConfigure {
            get {
                return ResourceManager.GetString("MBTNoPasswordsToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu option has not yet been implemented..
        /// </summary>
        internal static string MBTNotYetImplemented {
            get {
                return ResourceManager.GetString("MBTNotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The third party application software can only be modified by logging into the highest security level..
        /// </summary>
        internal static string MBTOptionThirdPartyUnauthorized {
            get {
                return ResourceManager.GetString("MBTOptionThirdPartyUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the communication port..
        /// </summary>
        internal static string MBTPortCloseFailed {
            get {
                return ResourceManager.GetString("MBTPortCloseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the communication port..
        /// </summary>
        internal static string MBTPortInitializationFailed {
            get {
                return ResourceManager.GetString("MBTPortInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release notes cannot be found..
        /// </summary>
        internal static string MBTReleaseNotesNotFound {
            get {
                return ResourceManager.GetString("MBTReleaseNotesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, please contact the system administrator..
        /// </summary>
        internal static string MBTSecurityLoginFailed {
            get {
                return ResourceManager.GetString("MBTSecurityLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and the verification password did not match, please try again..
        /// </summary>
        internal static string MBTSecurityMismatch {
            get {
                return ResourceManager.GetString("MBTSecurityMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password is incorrect, please try again..
        /// </summary>
        internal static string MBTSecurityPasswordIncorrect {
            get {
                return ResourceManager.GetString("MBTSecurityPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to log out?.
        /// </summary>
        internal static string MBTSecurityQueryLogOut {
            get {
                return ResourceManager.GetString("MBTSecurityQueryLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been successfully updated..
        /// </summary>
        internal static string MBTSecuritySuccess {
            get {
                return ResourceManager.GetString("MBTSecuritySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a target or press Cancel..
        /// </summary>
        internal static string MBTSelectTarget {
            get {
                return ResourceManager.GetString("MBTSelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There we no serial communication devices found on this computer..
        /// </summary>
        internal static string MBTSerialDeviceNotFound {
            get {
                return ResourceManager.GetString("MBTSerialDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new data dictionary cannot be selected while the PTU is {0}. Please disconnect and ensure that you are logged into the {1} account to complete this operation..
        /// </summary>
        internal static string MBTSetDataDictionaryNotAllowed {
            get {
                return ResourceManager.GetString("MBTSetDataDictionaryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new data dictionary cannot be selected while the PTU is running self tests. Please terminate the self tests, disconnect and ensure that you are logged into the {1} account to complete this operation..
        /// </summary>
        internal static string MBTSetDataDictionaryNotAllowedSelfTest {
            get {
                return ResourceManager.GetString("MBTSetDataDictionaryNotAllowedSelfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number of shortcut parameters were passed to the PTU. An attempt will be made to load the default data dictionary, &apos;{0}&apos;, instead..
        /// </summary>
        internal static string MBTShortcutParameterCountInvalid {
            get {
                return ResourceManager.GetString("MBTShortcutParameterCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display the help information..
        /// </summary>
        internal static string MBTShowHelpFileFailed {
            get {
                return ResourceManager.GetString("MBTShowHelpFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to select a new data dictionary. Please log into the {0} account to complete this operation..
        /// </summary>
        internal static string MBTUnauthorizedSetDataDictionary {
            get {
                return ResourceManager.GetString("MBTUnauthorizedSetDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-insert the Wibu-Key security device and log back in..
        /// </summary>
        internal static string MBTWibuBoxReInsert {
            get {
                return ResourceManager.GetString("MBTWibuBoxReInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wibu-Key security device has been removed. Access to the Engineering account is only allowed if a valid Wibu-Key security device is present. Logging out....
        /// </summary>
        internal static string MBTWibuBoxRemoved {
            get {
                return ResourceManager.GetString("MBTWibuBoxRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current project requires a Wibu-Key security device, however, the WibuKey Runtime Device Driver is not installed..
        /// </summary>
        internal static string MBTWibuKeyDeviceDriverNotInstalled {
            get {
                return ResourceManager.GetString("MBTWibuKeyDeviceDriverNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the system administrator or install the WibuKey Runtime Device Driver..
        /// </summary>
        internal static string MBTWibuKeyInstall {
            get {
                return ResourceManager.GetString("MBTWibuKeyInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the workset collection associated with the chart recorder..
        /// </summary>
        internal static string MBTWorksetCollectionChartRecorderLoadFailed {
            get {
                return ResourceManager.GetString("MBTWorksetCollectionChartRecorderLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the workset collection associated with the data stream parameters..
        /// </summary>
        internal static string MBTWorksetCollectionFaultLogLoadFailed {
            get {
                return ResourceManager.GetString("MBTWorksetCollectionFaultLogLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the workset collection associated with viewing and recording watch variables..
        /// </summary>
        internal static string MBTWorksetCollectionWatchLoadFailed {
            get {
                return ResourceManager.GetString("MBTWorksetCollectionWatchLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MetallicRaised {
            get {
                object obj = ResourceManager.GetObject("MetallicRaised", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModeDiagnostic {
            get {
                object obj = ResourceManager.GetObject("ModeDiagnostic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ModeOffline {
            get {
                object obj = ResourceManager.GetObject("ModeOffline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ModeOnline {
            get {
                object obj = ResourceManager.GetObject("ModeOnline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Modify {
            get {
                object obj = ResourceManager.GetObject("Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Offline {
            get {
                object obj = ResourceManager.GetObject("Offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Internet Explorer\iexplore.exe.
        /// </summary>
        internal static string PathDefaultBrowser {
            get {
                return ResourceManager.GetString("PathDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\FileZilla Client\filezilla.exe.
        /// </summary>
        internal static string PathDefaultFTPClient {
            get {
                return ResourceManager.GetString("PathDefaultFTPClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Bombardier.
        /// </summary>
        internal static string PathDefaultTCMSProgrammer {
            get {
                return ResourceManager.GetString("PathDefaultTCMSProgrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Documentation.
        /// </summary>
        internal static string PathRelativeDocumentation {
            get {
                return ResourceManager.GetString("PathRelativeDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;default&gt;.
        /// </summary>
        internal static string PathUseDefault {
            get {
                return ResourceManager.GetString("PathUseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Equipment (PTE).
        /// </summary>
        internal static string ProductNamePTE {
            get {
                return ResourceManager.GetString("ProductNamePTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Unit (PTU).
        /// </summary>
        internal static string ProductNamePTU {
            get {
                return ResourceManager.GetString("ProductNamePTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Record {
            get {
                object obj = ResourceManager.GetObject("Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Login.
        /// </summary>
        internal static string SecurityLogIn {
            get {
                return ResourceManager.GetString("SecurityLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Logout.
        /// </summary>
        internal static string SecurityLogOut {
            get {
                return ResourceManager.GetString("SecurityLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelfTest {
            get {
                object obj = ResourceManager.GetObject("SelfTest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target found on.
        /// </summary>
        internal static string TextNoTargetFoundOn {
            get {
                return ResourceManager.GetString("TextNoTargetFoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No targets found.
        /// </summary>
        internal static string TextNoTargetsFound {
            get {
                return ResourceManager.GetString("TextNoTargetsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for target on.
        /// </summary>
        internal static string TextSearchingForTargetOn {
            get {
                return ResourceManager.GetString("TextSearchingForTargetOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target found on.
        /// </summary>
        internal static string TextTargetFoundOn {
            get {
                return ResourceManager.GetString("TextTargetFoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target(s) found.
        /// </summary>
        internal static string TextTargetsFound {
            get {
                return ResourceManager.GetString("TextTargetsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Time {
            get {
                object obj = ResourceManager.GetObject("Time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Train {
            get {
                object obj = ResourceManager.GetObject("Train", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Watch {
            get {
                object obj = ResourceManager.GetObject("Watch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WibuKey {
            get {
                object obj = ResourceManager.GetObject("WibuKey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
