//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibuKey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WibuKey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MBCaptionError {
            get {
                return ResourceManager.GetString("MBCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MBCaptionInformation {
            get {
                return ResourceManager.GetString("MBCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MBCaptionWarning {
            get {
                return ResourceManager.GetString("MBCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A development Wibu-Key security device has been detected....
        /// </summary>
        internal static string MBTWibuBoxDevelopmentFound {
            get {
                return ResourceManager.GetString("MBTWibuBoxDevelopmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although a Wibu-Key security device was found, the appropriate slot was not programmed with the correct Firm and User codes..
        /// </summary>
        internal static string MBTWibuBoxFoundButInvalid {
            get {
                return ResourceManager.GetString("MBTWibuBoxFoundButInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Wibu-Key security device was not found..
        /// </summary>
        internal static string MBTWibuBoxNotFound {
            get {
                return ResourceManager.GetString("MBTWibuBoxNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wibu-Key has not been initialized..
        /// </summary>
        internal static string MBTWibuBoxNotInitialized {
            get {
                return ResourceManager.GetString("MBTWibuBoxNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the Engineering account is only allowed if a valid Wibu-Key security device is connected to either a parallel or USB port. Please shut down the application, insert a valid Wibu-Key security device and then retry this operation..
        /// </summary>
        internal static string MBTWibuBoxUserMessage {
            get {
                return ResourceManager.GetString("MBTWibuBoxUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wibu-Key did not encrypt the data correctly..
        /// </summary>
        internal static string MBTWibuKeyEncryptionInvalid {
            get {
                return ResourceManager.GetString("MBTWibuKeyEncryptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No WibuKey Subsystems found..
        /// </summary>
        internal static string MBTWibuKeySubsystemNotFound {
            get {
                return ResourceManager.GetString("MBTWibuKeySubsystemNotFound", resourceCulture);
            }
        }
    }
}
