#region --- Revision History ---
/*
 * 
 *  This document and its contents are the property of Bombardier Inc. or its subsidiaries and contains confidential, proprietary information.
 *  The reproduction, distribution, utilization or the communication of this document, or any part thereof, without express authorization is strictly prohibited.  
 *  Offenders will be held liable for the payment of damages.
 * 
 *  (C) 2010    Bombardier Inc. or its subsidiaries. All rights reserved.
 * 
 *  Solution:   Portable Test Unit
 * 
 *  Project:    Event
 * 
 *  File name:  FormOpenEventLog.cs
 * 
 *  Revision History
 *  ----------------
 */

/* 
 *  Date        Version Author          Comments
 *  12/03/10    1.0     K.McD           1.  First entry into TortoiseSVN.
 * 
 *  01/12/11    1.1     K.McD           1.  Bug fix SNCR001.84. Added the second parameter to the call to the System.Threading.WaitHandle.WaitOne() method, as advised by 
 *                                          the following blog entries: 
 *                                              (1) http://www.mikeplate.com/missingmethodexception-and-waitone/ and (2) 
 *                                              (2) http://blog.darrenstokes.com/2009/03/30/watch-out-for-those-waitone-overloads-when-you-need-backwards-compatibility 
 * 
 *  01/31/11    1.2     K.McD           1.  Auto-modified to accommodate the change in name of a number of resources.
 *                                      2.  Modified the constructor as the communication mutex is now defined within the CommunicationParent class rather than the 
 *                                          FormViewEventLog class.
 * 
 *  02/03/11    1.3     K.McD           1.  Modified a number of XML tags.
 *                                      2.  Replaced a hard coded text string with a string resource.
 *                                      3.  Included initial sort by date, most recent event first.
 *                                      4.  Modified the F3-Save function key event handler to support appending events to an existing file.
 *                                      5.  Modified the F4-Load function key event handler to support loading multiple saved event log files.
 *                                      6.  Standardized the function key event handlers to: display the wait cursor, enable the Checked property of the function key and 
 *                                          clear any status message.
 * 
 *  02/21/11    1.4     K.McD           1.  Auto-modified as a result of the method name change to AddList().
 * 
 *  02/28/11    1.5     K.McD           1.  Renamed this form.
 *                                      2.  Modified the image associated with the 'F4-Load' function key.
 *                                      3.  Modified the title text.
 *                                      4.  Removed any references to the m_DataGridViewEventLogSize member variable as this has been removed from the parent class.
 *                                      5.  Provide a class specific AddList() method rather that the method used in the parent class.
 * 
 *  03/02/11    1.6     K.McD           1.  Modified the constructor and the event handler associated with the 'F4-Load' function key such that the EventRecordList 
 *                                          property is sorted in descending date/time order once the events have been loaded from file. This ensures that the first row 
 *                                          of the DataGridView control is selected when the form is shown.
 * 
 *  03/18/11    1.7     K.McD           1.  Added support for the WinHlp32 help engine to display the help diagnostic information for the events and event variables.
 * 
 *                                      2.  Modified the event handler for the DataGridView SelectionChanged event to close any FormShowFlags forms that may be 
 *                                          open and to include a match for the event index in the Find() method when trying to locate the correct record in the 
 *                                          list of event records. This was added to cater for the case where multiple events with the same description and date/time 
 *                                          stamp are generated by the VCU, but with different event variable information e.g. in the case of the 'Inverter Fault' event.
 * 
 *                                      3.  Modified the event handler for the DataGridView CellContentDoubleClick event to include a check to determine 
 *                                          which column of the DataGridView has been selected by the user and then either: (a) display the diagnostic help 
 *                                          information associated with the selected event or (b) download and display the fault log associated with the 
 *                                          selected event, as appropriate.
 * 
 *                                      4.  Refactored the event handler for the DataGridView CellContentDoubleClick event such that the code responsible for 
 *                                          loading and displaying the fault log is now included in the newly created ShowFaultLog() method.
 * 
 *                                      5.  Modified the event handler for the DataGridView CellContentDoubleClick event to include a match for the event index 
 *                                          in the Find() method when trying to locate the correct record in the list of event records as per item 2.
 * 
 *  03/21/11    1.8     K.McD           1.  Modified the method used to find the selected event in the list of event records. The event record list is now 
 *                                          sorted by DateTime order, oldest event first and the event index of each record is updated so that it is unique and matches 
 *                                          the sort order of the list i.e. 0 will represent the oldest event, 1 the following event etc. When the user selects an event 
 *                                          from the DataGridView control the index of the event corresponding to the selected row is determined and the list of event 
 *                                          records is searched for a match.
 * 
 *                                      2.  Removed the event handlers associated with the DataGridView SecectionChanged and CellContentDoubleQuick events as these 
 *                                          are now identical to the event handlers in the parent class.
 * 
 *                                      3.  Added the override modifier to the ShowFaultLog() method.
 * 
 *  03/28/11    1.9     K.McD           1.  Modified the names of a number of local variables.
 *  
 *  07/27/11    1.10    K.McD           1.  Modified the class constructor to initialize the member variable that stores the number of common event variables that are 
 *                                          recorded for each event. Previous to this modification, whenever a user selected an event from the saved event data file the 
 *                                          event controls were re-drawn for every event variable associated with the selected event each time whereas after the 
 *                                          modification only the event specific event variables were re-drawn.
 *                                          
 *  09/30/11    1.11    K.McD           1.  Refactored the implementation of the IEventLogFile interface.
 *                                      2.  Modified the ShowFaultLog() method to update the FullFilename property of the WatchFile_t structure.
 *                                      
 *  10/26/11    1.12    K.McD           1.  SNCR002.41. Added checks to the event handlers associated with all ToolStripButton controls to ensure that the event handler 
 *                                          code is ignored if the Enabled property of the control is not asserted.                                      
 */

/*
 *  04/15/15    1.13    K.McD           References
 *                                      1.  Upgrade the PTU software to extend the support for the R188 project as defined in purchase order 4800010525-CU2/19.03.2015.
 * 
 *                                          1.  NK-U-6505 Section 5.1.3. Log File Naming. The filename of all event logs, fault logs, real time data etc will be modified
 *                                              to meet the KRC specification. This modification will be specific to the KRC project; for all other projects, the
 *                                              current naming convention will still apply.
 *                                              
 *                                          2.  NK-U-6505 Section 1.7.6. Data Sorting Capabilities. The proposal is to include an additional column in the spreadsheet
 *                                              that is used to view event logs (File/Open/Event Logs) that identifies the event log associated with the entry e.g.
 *                                              Maintenance, Engineering etc and allow the user to sort by this column. The format of the event log will obviously also
 *                                              have to be modified to include this information.
 *                                              
 *                                      2.  SNCR - R188 PTU [20-Mar-2015] Item 11. Loaded up a number of event logs supplied by PIPPC into the PTU and discovered that
 *                                          a number of duplicate records were added to the DataGridView control.
 *                                          
 *                                          When multiple event log files are loaded into the PTU, the event index field of a number of events may be modified
 *                                          as part of the process that ensures that each index is unique. This is carried out in both the constructor and the event
 *                                          handler for the [F4-Load] key 'Click' event of the FormOpenEventLog class. When loading additional files, the PTU checks
 *                                          for duplicate entries by comparing the: car identifier, log name, event name, date/time and event index of each imported
 *                                          record against the current list of entries, however, if the event index field of records in the current list has been
 *                                          modified as part of the previous load process, duplicate records will be added to the list as they will now have a different
 *                                          event index value. 
 *                                              
 *                                      Modifications
 *                                      1.  Modified the signature in the call to the General.DeriveName() method in the 'F3_Click' event handler. The original
 *                                          signature has been removed in order to simplify file naming. - Ref. 1.1.
 *                                      2.  Modified the constructor to set the 'Visible' property of the Log column of the DataGridView to the state of the 
 *                                          Parameter.ShowLogName property.
 *                                      3.  As it is essential that the 'Visible' property of the Log column of the DataGridView be set up before any Sort of
 *                                          the EventRecordList is performed, the Visible properties of both the CarIdentifier and the Log columns are now 
 *                                          set up at the start of the constructor, before the Sort of the EventRecordList is performed.
 *                                      4.  Modified the 'Shown' event handler to set up Width property of the DataGridView Panel depending upon whether the
 *                                          Log column of the DataGridView is visible or not.
 *                                      5.  Removed the section of code that updated the event indices of the event records to ensure that each index is unique
 *                                          and that index = 0 corresponds to the oldest entry in the list, from the constructor and the [F4-Load] event handler.
 */

/*
 *  05/11/15    1.14    K.McD           References
 *                                      1.  Upgrade the PTU software to extend the support for the R188 project as defined in purchase order
 *                                          4800010525-CU2/19.03.2015.
 *  
 *                                         1.  Changes to address the items outlined in the minutes of the meeting between BTPC, 
 *                                              Kawasaki Rail Car and NYTC on 12th April 2013 - MOC-0171:
 *                                              
 *                                              1.  MOC-0171-29/34. Kawasaki requested that any function that is not available to the current mode, either Maintenance
 *                                                  or Administrative, should not be displayed, or be 'greyed out'. BTPC agreed to review the software to ensure that
 *                                                  non-active menu items are ‘greyed out’ or not shown.
 *                                              
 *                                                  As a result of the review, it is proposed that the following modifications are carried out:
 *                                              
 *                                                  1.  The 'Select Data Dictionary' menu option should only visible when logged in as a BT engineer (Factory).
 *                                                      Also, when visible, it should only be enabled when not in onlide, offline or self test mode.
 *                                                      
 *                                                  2.  When in Self Test mode only the 'File/Exit', 'Help' and 'Login' main menu options should be enabled.
 *                                                  
 *                                                  3.  When displaying live event logs only the File/Exit', 'Configure/Worksets/Data Stream', 'Configure/Enumeration',
 *                                                      'Help', and 'Login' main menu options should be enabled.
 *                                                          
 *                                                  4.  When the Watch Window is paused or data is being recorded only the 'File/Exit', 'Help' and 'Login' main menu
 *                                                      options should be enabled.
 *  
 *                                      Modifications
 *                                      1.  Bug Fix. Added a call to RestoreMenuEnabled() in the FormOpenEventLog_Shown() event handler to ensure that the main
 *                                          menu options are not limited to those that are available when viewing live event logs, see 1.1.1.3, above.
 * 
 */
#endregion --- Revision History ---

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Threading;
using System.Windows.Forms;

using Common;
using Common.Configuration;
using Common.Forms;
using Common.UserControls;
using Event.Properties;

namespace Event.Forms
{
    /// <summary>
    /// Display the selected event log files using a <c>DataGridView</c> control.
    /// </summary>
    public partial class FormOpenEventLog : FormViewEventLog, IEventLogFile
    {
        #region --- Interfaces ---
        #region - [IEventLogFile] -
        #region - [Member Variables ] -
        /// <summary>
        /// The event log data.
        /// </summary>
        private EventLogFile_t m_EventLogFile;
        #endregion - [Member Variables ] -

        #region - [Methods] -
        /// <summary>
        /// Save the event log data to disk.
        /// </summary>
        public void SaveEventLogFile()
        {
            FileHandling.Serialize<EventLogFile_t>(EventLogFile.FullFilename, EventLogFile, FileHandling.FormatType.Xml);
        }
        #endregion - [Methods] -

        #region - [Properties] -
        /// <summary>
        /// Gets or sets the event log data.
        /// </summary>
        public EventLogFile_t EventLogFile
        {
            get { return m_EventLogFile; }
            set { m_EventLogFile = value; }
        }
        #endregion - [Properties] -
        #endregion - [IEventLogFile] -
        #endregion --- Interfaces ---

        #region --- Constructors ---
        /// <summary>
        /// Initialize a new instance of the class. Zero parameter constructor.
        /// </summary>
        public FormOpenEventLog()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Initialize a new instance of the class. Intialize the size of the various components, set-up the function keys and initialize the list of event records.
        /// </summary>
        public FormOpenEventLog(EventLogFile_t eventLogFile)
        {
            InitializeComponent();

            m_MutexDataGridView = new Mutex();
            m_MutexEventCount = new Mutex();

            #region - [DataGridView] -
            // Ensure that the DataGridView is set up before performing a sort.
            m_DataGridViewEventLog.Columns[ColumnIndexCarIdentifier].Visible = true;
            m_DataGridViewEventLog.Columns[ColumnIndexLog].Visible = (Parameter.ShowLogName) ? true : false;
            #endregion - [DataGridView] -

            EventLogFile = eventLogFile;
            EventRecordList = EventLogFile.EventRecordList;

            // Sort the list of events, most recent event first. This ensures that the first row of the DataGridView is selected when the event log is first shown.
            EventRecordList.Sort(CompareByDateTimeDescending);

            #region - [Size Definitions] -
            m_EventVariableControlSize = new VariableControlSize_t();
            m_EventVariableControlSize.Margin.Left = MarginLeftEventControl;
            m_EventVariableControlSize.Margin.Right = MarginRightEventControl;
            m_EventVariableControlSize.Margin.Top = MarginTopEventControl;
            m_EventVariableControlSize.Margin.Bottom = MarginBottomEventControl;
            m_EventVariableControlSize.WidthVariableNameField = WidthEventControlVariableNameField;
            m_EventVariableControlSize.WidthValueField = WidthEventControlValueField;
            m_EventVariableControlSize.WidthUnitsField = WidthEventControlUnitsField;
            m_EventVariableControlSize.Height = HeightEventControl;
            #endregion - [Size Definitions] -

            #region - [Function Keys] -
            DisplayFunctionKey(F3, Resources.FunctionKeyTextSave, Resources.FunctionKeyToolTipSaveEventLogs, Resources.Save);
            F3.Enabled = false;
            DisplayFunctionKey(F4, Resources.FunctionKeyTextLoad, Resources.FunctionKeyToolTipLoad, Resources.FolderOpen);
            DisplayFunctionKey(F12, Resources.FunctionKeyTextInfo, Resources.FunctionKeyToolTipInfo, Resources.FileInformation);
            #endregion - [Function Keys] -

            // InformationLabel 1  - Event Count
            DisplayLabel(InformationLabel1, Resources.InformationLegendEventCount, Color.FromKnownColor(KnownColor.Info));

            #region - [Titles] -
            Text = string.Format(Resources.TitleOpenEventLog, EventLogFile.Filename);
            m_TabPage1.Text = string.Empty;
            #endregion - [Titles] -

            m_CommonEventVariableCount = Lookup.EventTable.CommonEventVariableCount;
        }
        #endregion --- Constructors ---

        #region --- Cleanup ---
        /// <summary>
        /// Clean up the resources used by the form.
        /// </summary>
        /// <param name="disposing">True to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Cleanup(bool disposing)
        {
            try
            {
                if (disposing)
                {
                    // Cleanup managed objects by calling their Dispose() methods.
                    if (components != null)
                    {
                        components.Dispose();
                    }
                }

                // Whether called by consumer code or the garbage collector free all unmanaged resources and set the value of managed data members to null.

                #region --- Windows Form Designer Variables ---
                // Detach the event handler delegates.

                // Set the Windows Form Designer Variables to null.

                #endregion --- Windows Form Designer Variables ---
            }
            catch (Exception)
            {
                // Don't do anything, just ensure that an exception isn't thrown.
            }
            finally
            {
                base.Cleanup(disposing);
            }
        }
        #endregion --- Cleanup ---

        #region --- Delegated Methods ---
        #region - [Form] -
        /// <summary>
        /// Event handler for the form <c>Shown</c> event. Add the records contained in the specified file to the DataGridView control and show the number of events 
        /// saved in the list.
        /// </summary>
        /// <param name="sender">Reference to the object that raised the event.</param>
        /// <param name="e">Parameter passed from the object that raised the event.</param>
        private void FormOpenEventLog_Shown(object sender, EventArgs e)
        {
            // Skip, if the Dispose() method has been called.
            if (IsDisposed)
            {
                return;
            }

            Update();

            // Ensure that an exception isn't thrown when a child form is opened in the Visual Studio development environment.
            if (MainWindow == null)
            {
                return;
            }

            Cursor = Cursors.WaitCursor;

            #region - [DataGridView Panel] -
            // Get the combined width of all visible DataGridView columns.
            int dataGridViewWidth = 0;
            DataGridViewColumn dataGridViewColumn;
            for (int columnIndex = 0; columnIndex < m_DataGridViewEventLog.Columns.Count; columnIndex++)
            {
                dataGridViewColumn = m_DataGridViewEventLog.Columns[columnIndex];
                if (dataGridViewColumn.Visible == true)
                {
                    dataGridViewWidth += dataGridViewColumn.Width;
                }
            }

            m_PanelDataGridViewEventLog.Width = dataGridViewWidth + MarginRightDataGridViewControl;
            #endregion - [DataGridView Panel] -

            AddList(EventRecordList);

            // Sort by date/time, most recent event first.
            m_DataGridViewEventLog.Sort(m_DataGridViewEventLog.Columns[ColumnIndexDate], ListSortDirection.Descending);

            // Simulate a SelectionChanged event to display the event variables associated with the selected event.
            m_DataGridViewEventLog_SelectionChanged(m_DataGridViewEventLog, new EventArgs());

            // Write the car identifier associated with the data stream.
            MainWindow.WriteCarIdentifier(EventLogFile.Header.TargetConfiguration.CarIdentifier);

            RestoreMenuEnabled();

            m_DataGridViewEventLog.Focus();
            Cursor = Cursors.Default;
        }
        #endregion - [Form] -

        #region - [Function Keys] -
        #region - [F3-Save] -
        /// <summary>
        /// Event handler for the F3 function key. Save the current events to disk.
        /// </summary>
        /// <param name="sender">Reference to the object that raised the event.</param>
        /// <param name="e">Parameter passed from the object that raised the event.</param>
        protected override void F3_Click(object sender, EventArgs e)
        {
            // Skip, if the Dispose() method has been called.
            if (IsDisposed)
            {
                return;
            }

            // Skip if the key isn't enabled.
            if (F3.Enabled == false)
            {
                return;
            }

            Cursor = Cursors.WaitCursor;
            F3.Checked = true;

            // Clear the status message.
            if (MainWindow != null)
            {
                MainWindow.WriteStatusMessage(string.Empty);
            }

            bool userCancelled = true;

            DateTime createdTime = DateTime.Now;
            string defaultFilename = General.DeriveName(FileHeader.HeaderCurrent.TargetConfiguration.CarIdentifier, createdTime, CommonConstants.ExtensionEventLog,
                                                        string.Empty);
            string fullFilename = General.FileDialogSaveEventLog(defaultFilename, InitialDirectory.EventLogsWrite);
            if (fullFilename != string.Empty)
            {
                EventLogFile_t savedEventLogFile;
                Header_t header;

                userCancelled = CheckForAppend(fullFilename, ref createdTime, out header, out savedEventLogFile);
                if (userCancelled == true)
                {
                    return;
                }

                // Update the initial directory with the path of the selected file.
                InitialDirectory.EventLogsWrite = Path.GetDirectoryName(fullFilename);

                if (MainWindow != null)
                {
                    FileInfo fileInfo = new FileInfo(fullFilename);
                    MainWindow.WriteStatusMessage(string.Format(Resources.SMSaveFile, fileInfo.Name));
                }

                // Create a new event log file structure to store the event information.
                EventLogFile_t eventLogFile = new EventLogFile_t(header);

                // Check whether any saved events are to be added to the event log file structure.
                if (savedEventLogFile.EventRecordList.Count > 0)
                {
                    eventLogFile.AppendEventRecordList(savedEventLogFile.EventRecordList);
                }

                // Add the current records.
                eventLogFile.AppendEventRecordList(EventRecordList);

                // Only serialize the structure if it contains one or more events.
                if (eventLogFile.EventRecordList.Count > 0)
                {
                    // Serialize the data to the specified file.
                    FileHandling.Serialize<EventLogFile_t>(fullFilename, eventLogFile, FileHandling.FormatType.Xml);
                }
                else
                {
                    if (MainWindow != null)
                    {
                        MainWindow.WriteStatusMessage(Resources.SMEventListEmpty);
                    }
                }

                if (MainWindow != null)
                {
                    MainWindow.WriteStatusMessage(string.Empty);
                }
            }

            F3.Checked = false;
            Cursor = Cursors.Default;
        }
        #endregion - [F3-Save] -

        #region - [F4-Load] -
        /// <summary>
        /// Event handler for F4 function key. Load additional saved event logs.
        /// </summary>
        /// <param name="sender">Reference to the object that raised the event.</param>
        /// <param name="e">Parameter passed from the object that raised the event.</param>
        protected override void F4_Click(object sender, EventArgs e)
        {
            // Skip, if the Dispose() method has been called.
            if (IsDisposed)
            {
                return;
            }

            // Skip if the key isn't enabled.
            if (F4.Enabled == false)
            {
                return;
            }

            Cursor = Cursors.WaitCursor;
            F4.Checked = true;

            // Clear the status message.
            if (MainWindow != null)
            {
                MainWindow.WriteStatusMessage(string.Empty);
            }

            MenuInterfaceEvent menuInterfaceEvent = new MenuInterfaceEvent(MainWindow);

            // Create an event log file structure to hold the imported events.
            EventLogFile_t eventLogFile = menuInterfaceEvent.ImportEventLogFiles();
            if (eventLogFile.EventRecordList.Count <= 0)
            {
                F4.Checked = false;
                Cursor = Cursors.Default;
                return;
            }

            // Create a temporary event log file structure so that we can use the AppendEventRecordList() method to add the the imported events to the existing events 
            // while ignoring duplicate entries.
            EventLogFile_t temporaryEventLogFile = new EventLogFile_t();
            temporaryEventLogFile.EventRecordList = new List<EventRecord>();

            // Add the existing events to the list.
            temporaryEventLogFile.AppendEventRecordList(EventRecordList);

            // Append the imported events to the list ignoring duplicate entries.
            bool duplicationsFound;
            temporaryEventLogFile.AppendEventRecordList(eventLogFile.EventRecordList, out duplicationsFound);

            // Clear the EventRecordList property then add the events stored in the temporary event file structure.
            EventRecordList.Clear();
            EventRecordList.AddRange(temporaryEventLogFile.EventRecordList);

            // Sort the list of events, most recent event first. This ensures that the first row of the DataGridView is selected when the event log is first shown.
            EventRecordList.Sort(CompareByDateTimeDescending);

            ClearDataGridViewRows();
            AddList(EventRecordList);

            // Simulate a SelectionChanged event to display the event variables associated with the selected event.
            m_DataGridViewEventLog_SelectionChanged(m_DataGridViewEventLog, new EventArgs());

            F4.Checked = false;
            Cursor = Cursors.Default;
        }
        #endregion - [F4-Load] -

        #region - [F12-Header Information] -
        /// <summary>
        /// Event handler for F12 function key. Shows the form which displays the file header information.
        /// </summary>
        /// <param name="sender">Reference to the object that raised the event.</param>
        /// <param name="e">Parameter passed from the object that raised the event.</param>
        protected override void F12_Click(object sender, EventArgs e)
        {
            // Skip, if the Dispose() method has been called.
            if (IsDisposed)
            {
                return;
            }

            // Skip if the key isn't enabled.
            if (F12.Enabled == false)
            {
                return;
            }

            Cursor = Cursors.WaitCursor;
            F12.Checked = true;

            // Clear the status message.
            if (MainWindow != null)
            {
                MainWindow.WriteStatusMessage(string.Empty);
            }

            FormShowHeaderInformation formShowHeaderInformation = new FormShowHeaderInformation(EventLogFile.Header);
            formShowHeaderInformation.CalledFrom = this;
            formShowHeaderInformation.ShowDialog();
            F12.Checked = false;
            Cursor = Cursors.Default;
        }
        #endregion - [F12-Header Information] -
        #endregion - [Function Keys] -
        #endregion --- Delegated Methods ---

        #region --- Methods ---
        /// <summary>
        /// Add the specified records to the <c>DataGridView</c> control. If the specified list does not contain any records no action will be taken.
        /// </summary>
        /// <remarks>De-registers the <c>SelectionChanged</c> event handler while the rows are being added.</remarks>
        internal new void AddList(List<EventRecord> eventRecordList)
        {
            // Skip, if the Dispose() method has been called.
            if (IsDisposed)
            {
                return;
            }

            if (eventRecordList.Count <= 0)
            {
                return;
            }

            // Enable the Save function key.
            F3.Enabled = true;

            // Ensure that the SelectionChanged event is not triggered as a result of updating the rows of the DataGridView control.
            m_DataGridViewEventLog.SelectionChanged -= new EventHandler(m_DataGridViewEventLog_SelectionChanged);
            m_DataGridViewEventLog.SuspendLayout();

            // Add the specified list of event records to the DataGridView control.
            EventRecord eventRecord;
            for (short eventIndex = 0; eventIndex < eventRecordList.Count; eventIndex++)
            {
                eventRecord = eventRecordList[eventIndex];

                DataGridViewRow dataGridViewRow = Convert(eventRecord);

                // Add the new row to the DataGridView control.
                m_DataGridViewEventLog.Rows.Add(dataGridViewRow);
            }

            // If the sorted column hasn't yet been defined default to: sorted by index in descending order i.e. most recent  first.
            if (m_DataGridViewEventLog.SortedColumn == null)
            {
                m_DataGridViewEventLog.Sort(m_DataGridViewEventLog.Columns[0], System.ComponentModel.ListSortDirection.Descending);
            }
            else
            {
                System.ComponentModel.ListSortDirection listSortDirection;
                if (m_DataGridViewEventLog.SortOrder == SortOrder.Ascending)
                {
                    listSortDirection = System.ComponentModel.ListSortDirection.Ascending;
                }
                else
                {
                    listSortDirection = System.ComponentModel.ListSortDirection.Descending;
                }

                m_DataGridViewEventLog.Sort(m_DataGridViewEventLog.SortedColumn, listSortDirection);
            }

            m_DataGridViewEventLog.PerformLayout();
            m_DataGridViewEventLog.Update();

            // Re-register for the SelectionChanged event.
            m_DataGridViewEventLog.SelectionChanged += new EventHandler(m_DataGridViewEventLog_SelectionChanged);

            // If the Error Count information label is visible, display the error count.
            InformationLabel1.Text = m_DataGridViewEventLog.Rows.Count.ToString();
        }

        /// <summary>
        /// If a fault log data stream has been saved for the selected event record, retrieve the fault log from disk and call the form used to plot the fault log.
        /// </summary>
        /// <param name="selectedEventRecord">The selected event record.</param>
        protected override void ShowFaultLog(EventRecord selectedEventRecord)
        {
            // Skip, if the Dispose() method has been called.
            if (IsDisposed)
            {
                return;
            }

            // Skip, if a data stream hasn't been saved for the selected record.
            if ((selectedEventRecord == null) || (selectedEventRecord.StreamSaved == false))
            {
                MessageBox.Show(Resources.MBTFaultLogNotAvailable, Resources.MBCaptionInformation, MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            // ------------------------------------------------------------------------
            // Retrieve the data stream corresponding to the selected record from disk.
            // ------------------------------------------------------------------------
            string fullyQualifiedFaultLogFilename = General.GetFullyQualifiedFaultLogFilename(selectedEventRecord);
            FileInfo fileInfo = new FileInfo(fullyQualifiedFaultLogFilename);
            WatchFile_t watchFile;
            if (fileInfo.Exists)
            {
                // De-serialize the selected file.
                watchFile = FileHandling.Load<WatchFile_t>(fullyQualifiedFaultLogFilename, FileHandling.FormatType.Binary);

                // Ensure that the de-serialized file contains data.
                if (watchFile.DataStream.WatchFrameList == null)
                {
                    // File format is not recognised, report message.
                    MessageBox.Show(Resources.MBTInvalidFormat, Resources.MBCaptionError, MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }

                // Ensure that the selected log file is associated with the current project.
                if (watchFile.Header.ProjectInformation.ProjectIdentifier != Parameter.ProjectInformation.ProjectIdentifier)
                {
                    MessageBox.Show(Resources.MBTProjectIdMismatch, Resources.MBCaptionError, MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }

                watchFile.Filename = fileInfo.Name;
                watchFile.FullFilename = fileInfo.FullName;
            }
            else
            {
                MessageBox.Show(Resources.MBTDataStreamNotSaved, Resources.MBCaptionInformation, MessageBoxButtons.OK, MessageBoxIcon.Information);
                Cursor = Cursors.Default;
                return;
            }

            // -------------------------
            // Plot the saved fault log.
            // -------------------------
            try
            {
                FormOpenFaultLog formViewSavedFaultLog = new FormOpenFaultLog(watchFile);
                formViewSavedFaultLog.MdiParent = MdiParent;

                // The CalledFrom property is used to allow the called form to reference back to this form.
                formViewSavedFaultLog.CalledFrom = this;
                formViewSavedFaultLog.Show();
                Hide();
            }
            catch (Exception exception)
            {
                MessageBox.Show(Resources.MBTShowFaultLogFailed + CommonConstants.NewLine + CommonConstants.NewLine + exception.Message, Resources.MBCaptionInformation,
                                MessageBoxButtons.OK, MessageBoxIcon.Error);
            }

            return;
        }
        #endregion --- Methods ---
    }
}