//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Event.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConfigureEventFlags {
            get {
                object obj = ResourceManager.GetObject("ConfigureEventFlags", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataStream {
            get {
                object obj = ResourceManager.GetObject("DataStream", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event variable type associated with the record in invalid..
        /// </summary>
        internal static string EMEventVariableTypeInvalid {
            get {
                return ResourceManager.GetString("EMEventVariableTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the event flag information..
        /// </summary>
        internal static string EMGetFltFlagInfoFailed {
            get {
                return ResourceManager.GetString("EMGetFltFlagInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the event history..
        /// </summary>
        internal static string EMGetFltHistInfoFailed {
            get {
                return ResourceManager.GetString("EMGetFltHistInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample interval defined in the workset is invalid, assume a value of 1..
        /// </summary>
        internal static string EMSampleMultipleInvalid {
            get {
                return ResourceManager.GetString("EMSampleMultipleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the integrity check on the workset, please contact the system administrator..
        /// </summary>
        internal static string EMWorksetIntegrityCheckFailed {
            get {
                return ResourceManager.GetString("EMWorksetIntegrityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EventHistory {
            get {
                object obj = ResourceManager.GetObject("EventHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log Files.
        /// </summary>
        internal static string FileDialogOpenFilterEventLog {
            get {
                return ResourceManager.GetString("FileDialogOpenFilterEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stream Files.
        /// </summary>
        internal static string FileDialogOpenFilterFaultLog {
            get {
                return ResourceManager.GetString("FileDialogOpenFilterFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Event Log(s).
        /// </summary>
        internal static string FileDialogOpenTitleEventLog {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data Stream.
        /// </summary>
        internal static string FileDialogOpenTitleFaultLog {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileInformation {
            get {
                object obj = ResourceManager.GetObject("FileInformation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileRetrieve {
            get {
                object obj = ResourceManager.GetObject("FileRetrieve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string FunctionKeyTextClear {
            get {
                return ResourceManager.GetString("FunctionKeyTextClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string FunctionKeyTextEsc {
            get {
                return ResourceManager.GetString("FunctionKeyTextEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string FunctionKeyTextFlags {
            get {
                return ResourceManager.GetString("FunctionKeyTextFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string FunctionKeyTextHistory {
            get {
                return ResourceManager.GetString("FunctionKeyTextHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string FunctionKeyTextInfo {
            get {
                return ResourceManager.GetString("FunctionKeyTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init..
        /// </summary>
        internal static string FunctionKeyTextInitialize {
            get {
                return ResourceManager.GetString("FunctionKeyTextInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string FunctionKeyTextLoad {
            get {
                return ResourceManager.GetString("FunctionKeyTextLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FunctionKeyTextSave {
            get {
                return ResourceManager.GetString("FunctionKeyTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        internal static string FunctionKeyTextSetupStream {
            get {
                return ResourceManager.GetString("FunctionKeyTextSetupStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Clear Recent History].
        /// </summary>
        internal static string FunctionKeyToolTipClear {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Show Event Log Display].
        /// </summary>
        internal static string FunctionKeyToolTipEsc {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Configure Event Flags].
        /// </summary>
        internal static string FunctionKeyToolTipFlags {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Show Event History].
        /// </summary>
        internal static string FunctionKeyToolTipHistory {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Show Header Information].
        /// </summary>
        internal static string FunctionKeyToolTipInfo {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Clear Cumulative and Recent History].
        /// </summary>
        internal static string FunctionKeyToolTipInitialize {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Load Additional Event Log(s)].
        /// </summary>
        internal static string FunctionKeyToolTipLoad {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Save All Event Logs].
        /// </summary>
        internal static string FunctionKeyToolTipSaveEventLogs {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipSaveEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Save Data Stream].
        /// </summary>
        internal static string FunctionKeyToolTipSaveFaultLog {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipSaveFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Configure Data Stream].
        /// </summary>
        internal static string FunctionKeyToolTipSetupStream {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipSetupStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string InformationLegendDate {
            get {
                return ResourceManager.GetString("InformationLegendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events:.
        /// </summary>
        internal static string InformationLegendEventCount {
            get {
                return ResourceManager.GetString("InformationLegendEventCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Time:.
        /// </summary>
        internal static string InformationLegendTime {
            get {
                return ResourceManager.GetString("InformationLegendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Initialize {
            get {
                object obj = ResourceManager.GetObject("Initialize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string LegendAvailable {
            get {
                return ResourceManager.GetString("LegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string LegendCount {
            get {
                return ResourceManager.GetString("LegendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Event Log:.
        /// </summary>
        internal static string LegendCurrentEventLog {
            get {
                return ResourceManager.GetString("LegendCurrentEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string LegendOf {
            get {
                return ResourceManager.GetString("LegendOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        internal static string LegendTotalCount {
            get {
                return ResourceManager.GetString("LegendTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MBCaptionError {
            get {
                return ResourceManager.GetString("MBCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MBCaptionInformation {
            get {
                return ResourceManager.GetString("MBCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MBCaptionQuestion {
            get {
                return ResourceManager.GetString("MBCaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MBCaptionWarning {
            get {
                return ResourceManager.GetString("MBCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes - append the current events to the existing records. No - replace the existing records..
        /// </summary>
        internal static string MBTAppendOverwrite {
            get {
                return ResourceManager.GetString("MBTAppendOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file contains data associated with a different project. The current data will not be appended to the file and the save operation will be cancelled..
        /// </summary>
        internal static string MBTAppendProjectMismatch {
            get {
                return ResourceManager.GetString("MBTAppendProjectMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to clear all event logs?.
        /// </summary>
        internal static string MBTConfirmClearEventLogs {
            get {
                return ResourceManager.GetString("MBTConfirmClearEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to initialize all event logs?.
        /// </summary>
        internal static string MBTConfirmInitializeEventLogs {
            get {
                return ResourceManager.GetString("MBTConfirmInitializeEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data stream file associated with the selected event cannot be found..
        /// </summary>
        internal static string MBTDataStreamNotSaved {
            get {
                return ResourceManager.GetString("MBTDataStreamNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more event flags have been modified. Do you want to update the Vehicle Control Unit?.
        /// </summary>
        internal static string MBTEventFlagsChanged {
            get {
                return ResourceManager.GetString("MBTEventFlagsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clear one or more of the event logs..
        /// </summary>
        internal static string MBTEventLogClearFailed {
            get {
                return ResourceManager.GetString("MBTEventLogClearFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download the selected event log..
        /// </summary>
        internal static string MBTEventLogDownloadFailed {
            get {
                return ResourceManager.GetString("MBTEventLogDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize one or more of the event logs..
        /// </summary>
        internal static string MBTEventLogInitializeFailed {
            get {
                return ResourceManager.GetString("MBTEventLogInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current events were not successfully saved. Do you want to continue?.
        /// </summary>
        internal static string MBTEventLogSaveFailed {
            get {
                return ResourceManager.GetString("MBTEventLogSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Events table of the data dictionary does not contain an event corresponding to LOGID = {0}, TASKID = {1} and EVENTID = {2}..
        /// </summary>
        internal static string MBTEventNotFound {
            get {
                return ResourceManager.GetString("MBTEventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data stream available for the selected event..
        /// </summary>
        internal static string MBTFaultLogNotAvailable {
            get {
                return ResourceManager.GetString("MBTFaultLogNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to serialize the data stream to disk..
        /// </summary>
        internal static string MBTFaultLogSerializationFailed {
            get {
                return ResourceManager.GetString("MBTFaultLogSerializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a new workset or modify the current workset and retry..
        /// </summary>
        internal static string MBTFaultLogWorksetEditRequest {
            get {
                return ResourceManager.GetString("MBTFaultLogWorksetEditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of watch variables defined in the workset exceeds the number that are supported by the current event log..
        /// </summary>
        internal static string MBTFaultLogWorksetWatchVariablesMaxExceeded {
            get {
                return ResourceManager.GetString("MBTFaultLogWorksetWatchVariablesMaxExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of the file cannot be read. Do you want to over-write the file?.
        /// </summary>
        internal static string MBTFileCorrupt {
            get {
                return ResourceManager.GetString("MBTFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of &apos;{0}&apos; is not recognized. This file will not be imported..
        /// </summary>
        internal static string MBTFormatNotRecognized {
            get {
                return ResourceManager.GetString("MBTFormatNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the default data stream parameters..
        /// </summary>
        internal static string MBTGetDefaultStreamParametersFailed {
            get {
                return ResourceManager.GetString("MBTGetDefaultStreamParametersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the data stream associated with the &apos;{0}&apos; event..
        /// </summary>
        internal static string MBTGetStreamFailed {
            get {
                return ResourceManager.GetString("MBTGetStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the selected file is not recognized..
        /// </summary>
        internal static string MBTInvalidFormat {
            get {
                return ResourceManager.GetString("MBTInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This log file type is not supported..
        /// </summary>
        internal static string MBTLogFileTypeNotSupported {
            get {
                return ResourceManager.GetString("MBTLogFileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify the data stream parameters..
        /// </summary>
        internal static string MBTModifyFaultLogParametersFailed {
            get {
                return ResourceManager.GetString("MBTModifyFaultLogParametersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data stream parameters have been successfully updated..
        /// </summary>
        internal static string MBTModifyFaultLogParametersSuccess {
            get {
                return ResourceManager.GetString("MBTModifyFaultLogParametersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to show the selected data stream..
        /// </summary>
        internal static string MBTOpenFaultLogFailed {
            get {
                return ResourceManager.GetString("MBTOpenFaultLogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project identifier associated with the selected file does not match that of the current configuration..
        /// </summary>
        internal static string MBTProjectIdMismatch {
            get {
                return ResourceManager.GetString("MBTProjectIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project identifier associated with &apos;{0}&apos; does not match that of the current configuration. This file will not be imported..
        /// </summary>
        internal static string MBTProjectIdMismatchMultipleImport {
            get {
                return ResourceManager.GetString("MBTProjectIdMismatchMultipleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current events before proceeding?.
        /// </summary>
        internal static string MBTQueryEventLogSave {
            get {
                return ResourceManager.GetString("MBTQueryEventLogSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to modify the data stream parameters to the selected setting?.
        /// </summary>
        internal static string MBTQueryModifyFaultLogParameters {
            get {
                return ResourceManager.GetString("MBTQueryModifyFaultLogParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been cancelled as the data stream associated with the &apos;{0}&apos; event could not be downloaded..
        /// </summary>
        internal static string MBTSaveDataStreamsFailed {
            get {
                return ResourceManager.GetString("MBTSaveDataStreamsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the event flag associated with the &apos;{0}&apos; event..
        /// </summary>
        internal static string MBTSetFaultFlagsFailed {
            get {
                return ResourceManager.GetString("MBTSetFaultFlagsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display the data stream..
        /// </summary>
        internal static string MBTShowFaultLogFailed {
            get {
                return ResourceManager.GetString("MBTShowFaultLogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was cancelled by the user..
        /// </summary>
        internal static string MBTUserCancelled {
            get {
                return ResourceManager.GetString("MBTUserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display the event logs..
        /// </summary>
        internal static string MBTViewEventLogFailed {
            get {
                return ResourceManager.GetString("MBTViewEventLogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified watch variable is not defined in the current data dictionary..
        /// </summary>
        internal static string MBTWatchVariableNotDefined {
            get {
                return ResourceManager.GetString("MBTWatchVariableNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Modify {
            get {
                object obj = ResourceManager.GetObject("Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fault - Port Locked..
        /// </summary>
        internal static string SMCommunicationFaultPortLocked {
            get {
                return ResourceManager.GetString("SMCommunicationFaultPortLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fault - Read Timeout..
        /// </summary>
        internal static string SMCommunicationFaultReadTimeout {
            get {
                return ResourceManager.GetString("SMCommunicationFaultReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving &apos;{0}&apos; log data stream {1} of {2}..
        /// </summary>
        internal static string SMDataStreamSaveXofY {
            get {
                return ResourceManager.GetString("SMDataStreamSaveXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the &apos;{0}&apos; log data streams..
        /// </summary>
        internal static string SMDataStreamsSave {
            get {
                return ResourceManager.GetString("SMDataStreamsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events..
        /// </summary>
        internal static string SMEventListEmpty {
            get {
                return ResourceManager.GetString("SMEventListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving the &apos;{0}&apos; log..
        /// </summary>
        internal static string SMEventLogRetrieve {
            get {
                return ResourceManager.GetString("SMEventLogRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing the &apos;{0}&apos; log..
        /// </summary>
        internal static string SMEventLogsClear {
            get {
                return ResourceManager.GetString("SMEventLogsClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the &apos;{0}&apos; log..
        /// </summary>
        internal static string SMEventLogsInitialize {
            get {
                return ResourceManager.GetString("SMEventLogsInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading &apos;{0}&apos;..
        /// </summary>
        internal static string SMLoadFile {
            get {
                return ResourceManager.GetString("SMLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving &apos;{0}&apos;..
        /// </summary>
        internal static string SMSaveFile {
            get {
                return ResourceManager.GetString("SMSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by &apos;{0}&apos; in ascending order, most recent event first..
        /// </summary>
        internal static string SMSortOrdedAscending {
            get {
                return ResourceManager.GetString("SMSortOrdedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by &apos;{0}&apos; in descending order, oldest event first..
        /// </summary>
        internal static string SMSortOrdedDescending {
            get {
                return ResourceManager.GetString("SMSortOrdedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by date/time, oldest event first..
        /// </summary>
        internal static string SMSortOrderDateTimeAscending {
            get {
                return ResourceManager.GetString("SMSortOrderDateTimeAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by date/time, most recent event first..
        /// </summary>
        internal static string SMSortOrderDateTimeDescending {
            get {
                return ResourceManager.GetString("SMSortOrderDateTimeDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string TextReset {
            get {
                return ResourceManager.GetString("TextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string TextSet {
            get {
                return ResourceManager.GetString("TextSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure - Data Stream Parameters.
        /// </summary>
        internal static string TitleConfigureFaultLogParameters {
            get {
                return ResourceManager.GetString("TitleConfigureFaultLogParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy - Data Stream Workset.
        /// </summary>
        internal static string TitleCopyFaultLogWorkset {
            get {
                return ResourceManager.GetString("TitleCopyFaultLogWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New - Data Stream Workset.
        /// </summary>
        internal static string TitleCreateFaultLogWorkset {
            get {
                return ResourceManager.GetString("TitleCreateFaultLogWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify - Data Stream Workset.
        /// </summary>
        internal static string TitleEditFaultLogWorksets {
            get {
                return ResourceManager.GetString("TitleEditFaultLogWorksets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event History.
        /// </summary>
        internal static string TitleEventHistory {
            get {
                return ResourceManager.GetString("TitleEventHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics/Data Stream: {0}.
        /// </summary>
        internal static string TitleFaultLog {
            get {
                return ResourceManager.GetString("TitleFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Event Log: {0}.
        /// </summary>
        internal static string TitleOpenEventLog {
            get {
                return ResourceManager.GetString("TitleOpenEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Data Stream: {0}.
        /// </summary>
        internal static string TitleOpenFaultLog {
            get {
                return ResourceManager.GetString("TitleOpenFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename - Data Stream Workset.
        /// </summary>
        internal static string TitleRenameFaultLogWorkset {
            get {
                return ResourceManager.GetString("TitleRenameFaultLogWorkset", resourceCulture);
            }
        }
    }
}
