//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bookmark {
            get {
                object obj = ResourceManager.GetObject("Bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0; Data Source =.
        /// </summary>
        internal static string ConnectionStringDataDictionary {
            get {
                return ResourceManager.GetString("ConnectionStringDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreateNew {
            get {
                object obj = ResourceManager.GetObject("CreateNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string DescriptionSecurityLevel0 {
            get {
                return ResourceManager.GetString("DescriptionSecurityLevel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        internal static string DescriptionSecurityLevel1 {
            get {
                return ResourceManager.GetString("DescriptionSecurityLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string DescriptionSecurityLevel2 {
            get {
                return ResourceManager.GetString("DescriptionSecurityLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string DescriptionSecurityLevel3 {
            get {
                return ResourceManager.GetString("DescriptionSecurityLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the mode of the chart recorder..
        /// </summary>
        internal static string EMChartModeGetFailed {
            get {
                return ResourceManager.GetString("EMChartModeGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the mode of the chart recorder..
        /// </summary>
        internal static string EMChartModeSetFailed {
            get {
                return ResourceManager.GetString("EMChartModeSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array is too small..
        /// </summary>
        internal static string EMCyclicQueueInvalidArraySize {
            get {
                return ResourceManager.GetString("EMCyclicQueueInvalidArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer size must be a positive value..
        /// </summary>
        internal static string EMCyclicQueueInvalidBufferSize {
            get {
                return ResourceManager.GetString("EMCyclicQueueInvalidBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array rank must be 1..
        /// </summary>
        internal static string EMCyclicQueueInvalidRank {
            get {
                return ResourceManager.GetString("EMCyclicQueueInvalidRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot dequeue an empty queue..
        /// </summary>
        internal static string EMCyclicQueueQueueEmptyDequeue {
            get {
                return ResourceManager.GetString("EMCyclicQueueQueueEmptyDequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot peek an empty queue..
        /// </summary>
        internal static string EMCyclicQueueQueueEmptyPeek {
            get {
                return ResourceManager.GetString("EMCyclicQueueQueueEmptyPeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file cannot be found..
        /// </summary>
        internal static string EMFileNotFound {
            get {
                return ResourceManager.GetString("EMFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the target configuration..
        /// </summary>
        internal static string EMGetTargetConfigurationFailed {
            get {
                return ResourceManager.GetString("EMGetTargetConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the specified help file is invalid..
        /// </summary>
        internal static string EMHelpFileFormatInvalid {
            get {
                return ResourceManager.GetString("EMHelpFileFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System does not support multiple selections..
        /// </summary>
        internal static string EMListBoxMultipleSelectionNotSupported {
            get {
                return ResourceManager.GetString("EMListBoxMultipleSelectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference is null..
        /// </summary>
        internal static string EMNullReference {
            get {
                return ResourceManager.GetString("EMNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of range..
        /// </summary>
        internal static string EMOutOfRange {
            get {
                return ResourceManager.GetString("EMOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the communication port..
        /// </summary>
        internal static string EMPortCloseFailed {
            get {
                return ResourceManager.GetString("EMPortCloseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the communication port..
        /// </summary>
        internal static string EMPortInitializationFailed {
            get {
                return ResourceManager.GetString("EMPortInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the chart index associated with channel {0} of the chart recorder..
        /// </summary>
        internal static string EMSetChartIndexFailed {
            get {
                return ResourceManager.GetString("EMSetChartIndexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the scale of a chart recorder channel..
        /// </summary>
        internal static string EMSetChartScaleFailed {
            get {
                return ResourceManager.GetString("EMSetChartScaleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the WinHlp32 help engine was unsuccessful..
        /// </summary>
        internal static string EMWinHlp32CallFailed {
            get {
                return ResourceManager.GetString("EMWinHlp32CallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WinHlp32 help engine has not been initialized..
        /// </summary>
        internal static string EMWinHlp32NotInitialized {
            get {
                return ResourceManager.GetString("EMWinHlp32NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the integrity check on the workset. Please contact the system administrator..
        /// </summary>
        internal static string EMWorksetIntegrityCheckFailed {
            get {
                return ResourceManager.GetString("EMWorksetIntegrityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Dictionary Files.
        /// </summary>
        internal static string FileDialogOpenFilterDataDictionary {
            get {
                return ResourceManager.GetString("FileDialogOpenFilterDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Database Files.
        /// </summary>
        internal static string FileDialogOpenFilterEngineeringDatabase {
            get {
                return ResourceManager.GetString("FileDialogOpenFilterEngineeringDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data Dictionary.
        /// </summary>
        internal static string FileDialogOpenTitleDataDictionary {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Engineering Database.
        /// </summary>
        internal static string FileDialogOpenTitleEngineeringDatabase {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleEngineeringDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project Configuration Database.
        /// </summary>
        internal static string FileDialogOpenTitleProjectConfigurationDatabase {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleProjectConfigurationDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 Color Bitmap.
        /// </summary>
        internal static string FileDialogSaveFilterBMP {
            get {
                return ResourceManager.GetString("FileDialogSaveFilterBMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Dictionary File.
        /// </summary>
        internal static string FileDialogSaveFilterDataDictionary {
            get {
                return ResourceManager.GetString("FileDialogSaveFilterDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log.
        /// </summary>
        internal static string FileDialogSaveFilterEventLog {
            get {
                return ResourceManager.GetString("FileDialogSaveFilterEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stream.
        /// </summary>
        internal static string FileDialogSaveFilterFaultLog {
            get {
                return ResourceManager.GetString("FileDialogSaveFilterFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG File.
        /// </summary>
        internal static string FileDialogSaveFilterJPEG {
            get {
                return ResourceManager.GetString("FileDialogSaveFilterJPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Watch File.
        /// </summary>
        internal static string FileDialogSaveFilterRecordedWatchFile {
            get {
                return ResourceManager.GetString("FileDialogSaveFilterRecordedWatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated Data Stream.
        /// </summary>
        internal static string FileDialogSaveFilterSimulatedFaultLog {
            get {
                return ResourceManager.GetString("FileDialogSaveFilterSimulatedFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data Dictionary.
        /// </summary>
        internal static string FileDialogSaveTitleDataDictionary {
            get {
                return ResourceManager.GetString("FileDialogSaveTitleDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Event Log.
        /// </summary>
        internal static string FileDialogSaveTitleEventLog {
            get {
                return ResourceManager.GetString("FileDialogSaveTitleEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data Stream.
        /// </summary>
        internal static string FileDialogSaveTitleFaultLog {
            get {
                return ResourceManager.GetString("FileDialogSaveTitleFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image File.
        /// </summary>
        internal static string FileDialogSaveTitleImageFile {
            get {
                return ResourceManager.GetString("FileDialogSaveTitleImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Recorded Watch Data.
        /// </summary>
        internal static string FileDialogSaveTitleRecordedWatchFile {
            get {
                return ResourceManager.GetString("FileDialogSaveTitleRecordedWatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Simulated Data Stream.
        /// </summary>
        internal static string FileDialogSaveTitleSimulatedFaultLog {
            get {
                return ResourceManager.GetString("FileDialogSaveTitleSimulatedFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileInformation {
            get {
                object obj = ResourceManager.GetObject("FileInformation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workset.
        /// </summary>
        internal static string FileMnemonicDefaultWorkset {
            get {
                return ResourceManager.GetString("FileMnemonicDefaultWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.xml.
        /// </summary>
        internal static string FilenameDefaultDataDictionary {
            get {
                return ResourceManager.GetString("FilenameDefaultDataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.xml.
        /// </summary>
        internal static string FilenameDefaultDebugFile {
            get {
                return ResourceManager.GetString("FilenameDefaultDebugFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Equipment - Software User Manual.pdf.
        /// </summary>
        internal static string FilenameSoftwareUserManualPTE {
            get {
                return ResourceManager.GetString("FilenameSoftwareUserManualPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Test Unit - Software User Manual.pdf.
        /// </summary>
        internal static string FilenameSoftwareUserManualPTU {
            get {
                return ResourceManager.GetString("FilenameSoftwareUserManualPTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string FunctionKeyTextEdit {
            get {
                return ResourceManager.GetString("FunctionKeyTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string FunctionKeyTextEsc {
            get {
                return ResourceManager.GetString("FunctionKeyTextEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string FunctionKeyTextFirst {
            get {
                return ResourceManager.GetString("FunctionKeyTextFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string FunctionKeyTextInfo {
            get {
                return ResourceManager.GetString("FunctionKeyTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string FunctionKeyTextLast {
            get {
                return ResourceManager.GetString("FunctionKeyTextLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor.
        /// </summary>
        internal static string FunctionKeyTextMultiCursor {
            get {
                return ResourceManager.GetString("FunctionKeyTextMultiCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string FunctionKeyTextNext {
            get {
                return ResourceManager.GetString("FunctionKeyTextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string FunctionKeyTextPause {
            get {
                return ResourceManager.GetString("FunctionKeyTextPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string FunctionKeyTextPlay {
            get {
                return ResourceManager.GetString("FunctionKeyTextPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev..
        /// </summary>
        internal static string FunctionKeyTextPrevious {
            get {
                return ResourceManager.GetString("FunctionKeyTextPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        internal static string FunctionKeyTextReplay {
            get {
                return ResourceManager.GetString("FunctionKeyTextReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FunctionKeyTextSave {
            get {
                return ResourceManager.GetString("FunctionKeyTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        internal static string FunctionKeyTextTrip {
            get {
                return ResourceManager.GetString("FunctionKeyTextTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTPlot.
        /// </summary>
        internal static string FunctionKeyTextYTPlot {
            get {
                return ResourceManager.GetString("FunctionKeyTextYTPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Modify Current Workset].
        /// </summary>
        internal static string FunctionKeyToolTipEdit {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Modify Plot Layout].
        /// </summary>
        internal static string FunctionKeyToolTipEditPlotLayout {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipEditPlotLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Return to Event Log Display].
        /// </summary>
        internal static string FunctionKeyToolTipEsc {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FunctionKeyToolTipFirst {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Show Header Information].
        /// </summary>
        internal static string FunctionKeyToolTipInfo {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FunctionKeyToolTipLast {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Toggle Single/Multiple Cursors].
        /// </summary>
        internal static string FunctionKeyToolTipMultiCursor {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipMultiCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FunctionKeyToolTipNext {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Pause Screen Update].
        /// </summary>
        internal static string FunctionKeyToolTipPause {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Pause Playback].
        /// </summary>
        internal static string FunctionKeyToolTipPauseReplay {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipPauseReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Playback in Real Time].
        /// </summary>
        internal static string FunctionKeyToolTipPlay {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FunctionKeyToolTipPrevious {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Replay Frames in Single-Step Mode].
        /// </summary>
        internal static string FunctionKeyToolTipReplay {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FunctionKeyToolTipSave {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Go to Trip Condition].
        /// </summary>
        internal static string FunctionKeyToolTipTrip {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Show the Plot of Y Values Against Time].
        /// </summary>
        internal static string FunctionKeyToolTipYTPlot {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipYTPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stream.
        /// </summary>
        internal static string HeaderTextDataStream {
            get {
                return ResourceManager.GetString("HeaderTextDataStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string InformationLegendDate {
            get {
                return ResourceManager.GetString("InformationLegendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string InformationLegendDuration {
            get {
                return ResourceManager.GetString("InformationLegendDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame:.
        /// </summary>
        internal static string InformationLegendFrame {
            get {
                return ResourceManager.GetString("InformationLegendFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec. Start:.
        /// </summary>
        internal static string InformationLegendRecordingStartTime {
            get {
                return ResourceManager.GetString("InformationLegendRecordingStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string InformationLegendRTC {
            get {
                return ResourceManager.GetString("InformationLegendRTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        internal static string InformationLegendStartTime {
            get {
                return ResourceManager.GetString("InformationLegendStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop:.
        /// </summary>
        internal static string InformationLegendStopTime {
            get {
                return ResourceManager.GetString("InformationLegendStopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Time:.
        /// </summary>
        internal static string InformationLegendTime {
            get {
                return ResourceManager.GetString("InformationLegendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keys {
            get {
                object obj = ResourceManager.GetObject("Keys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string LegendAvailable {
            get {
                return ResourceManager.GetString("LegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string LegendColumn {
            get {
                return ResourceManager.GetString("LegendColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback:.
        /// </summary>
        internal static string LegendPlayback {
            get {
                return ResourceManager.GetString("LegendPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        internal static string LegendTotalCount {
            get {
                return ResourceManager.GetString("LegendTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Workset:.
        /// </summary>
        internal static string LegendWorkset {
            get {
                return ResourceManager.GetString("LegendWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightMetallic {
            get {
                object obj = ResourceManager.GetObject("LightMetallic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MBCaptionConfirm {
            get {
                return ResourceManager.GetString("MBCaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MBCaptionError {
            get {
                return ResourceManager.GetString("MBCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MBCaptionInformation {
            get {
                return ResourceManager.GetString("MBCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MBCaptionQuestion {
            get {
                return ResourceManager.GetString("MBCaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MBCaptionWarning {
            get {
                return ResourceManager.GetString("MBCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This context menu option is only applicable to bitmask watch variables..
        /// </summary>
        internal static string MBTBitmaskOnly {
            get {
                return ResourceManager.GetString("MBTBitmaskOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project identifier associated with the selected data dictionary is not applicable to this project, please select a project configuration file that is associated with the {0} project, e.g. &apos;{0}VC0123.xml&apos;..
        /// </summary>
        internal static string MBTConfigProjectAsParameterMismatch {
            get {
                return ResourceManager.GetString("MBTConfigProjectAsParameterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default configuration file, &apos;{0}&apos;, or any of the project default configuration files, &apos;&lt;project-identifier&gt;.{0}&apos;, are not valid selections for this menu option. Please select a project configuration file that is based upon the following filename format: &apos;&lt;project-identifier&gt;VC&lt;4-digit-version-reference&gt;.xml&apos; e.g. &apos;CTPAVC0193.xml&apos;..
        /// </summary>
        internal static string MBTConfigSelectionInvalid {
            get {
                return ResourceManager.GetString("MBTConfigSelectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the XML configuration file..
        /// </summary>
        internal static string MBTConfigurationFileLoadFailed {
            get {
                return ResourceManager.GetString("MBTConfigurationFileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to modify the &apos;{0}&apos; workset ?.
        /// </summary>
        internal static string MBTConfirmWorksetModify {
            get {
                return ResourceManager.GetString("MBTConfirmWorksetModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open a connection to the specified database..
        /// </summary>
        internal static string MBTDatabaseConnectionFailed {
            get {
                return ResourceManager.GetString("MBTDatabaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default data dictionary file could not be found. Please contact the system administrator..
        /// </summary>
        internal static string MBTDefaultDataDictionaryNotFound {
            get {
                return ResourceManager.GetString("MBTDefaultDataDictionaryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry corresponding to the time of the trip could not be found..
        /// </summary>
        internal static string MBTFrameNotFound {
            get {
                return ResourceManager.GetString("MBTFrameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display the help information..
        /// </summary>
        internal static string MBTHelpFail {
            get {
                return ResourceManager.GetString("MBTHelpFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The help document cannot be found..
        /// </summary>
        internal static string MBTHelpFileNotFound {
            get {
                return ResourceManager.GetString("MBTHelpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the system administrator or use the &apos;Configure/Worksets&apos; menu option to correct the workset(s)..
        /// </summary>
        internal static string MBTInstructionConfigureWorksets {
            get {
                return ResourceManager.GetString("MBTInstructionConfigureWorksets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a workset..
        /// </summary>
        internal static string MBTInstructionSelectWorkset {
            get {
                return ResourceManager.GetString("MBTInstructionSelectWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to modify the workset..
        /// </summary>
        internal static string MBTInsufficientPrivilegesModify {
            get {
                return ResourceManager.GetString("MBTInsufficientPrivilegesModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the selected file is not recognized..
        /// </summary>
        internal static string MBTInvalidFormat {
            get {
                return ResourceManager.GetString("MBTInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid references are: {0}.
        /// </summary>
        internal static string MBTInvalidOldIdentifierList {
            get {
                return ResourceManager.GetString("MBTInvalidOldIdentifierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout will be modified for the current session, however, these changes will not be committed to disk..
        /// </summary>
        internal static string MBTLayoutChangesNotSaved {
            get {
                return ResourceManager.GetString("MBTLayoutChangesNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is outside of the allowable range..
        /// </summary>
        internal static string MBTOutsideOfRange {
            get {
                return ResourceManager.GetString("MBTOutsideOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project identifier associated with the selected file does not match that of the current configuration..
        /// </summary>
        internal static string MBTProjectIdMismatch {
            get {
                return ResourceManager.GetString("MBTProjectIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected workset is defined as the default workset. Are you sure that you want to delete this workset ?.
        /// </summary>
        internal static string MBTQueryDeleteDefaultWorkset {
            get {
                return ResourceManager.GetString("MBTQueryDeleteDefaultWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string MBTQueryDeleteWorkset {
            get {
                return ResourceManager.GetString("MBTQueryDeleteWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected workset is defined as the default workset. Are you sure that you want to modify this workset ?.
        /// </summary>
        internal static string MBTQueryEditDefaultWorkset {
            get {
                return ResourceManager.GetString("MBTQueryEditDefaultWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to rename the &apos;{0}&apos; workset ?.
        /// </summary>
        internal static string MBTQueryWorksetRename {
            get {
                return ResourceManager.GetString("MBTQueryWorksetRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected watch variable is read-only..
        /// </summary>
        internal static string MBTReadOnly {
            get {
                return ResourceManager.GetString("MBTReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PTUDLL32 dynamic link library supplied with the project does not support programmable setting of the watch variable size. The retrieved data may have incorrect values..
        /// </summary>
        internal static string MBTSetWatchSizeNotSupported {
            get {
                return ResourceManager.GetString("MBTSetWatchSizeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML data dictionary was successfully created..
        /// </summary>
        internal static string MBTSuccessDataDictionaryCreate {
            get {
                return ResourceManager.GetString("MBTSuccessDataDictionaryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion cannot proceed as one or more columns of the &apos;{0}&apos; table are missing. Please update the table using the equivalent table contained within the &apos;E1 Database Modifications.E1&apos; database as a template..
        /// </summary>
        internal static string MBTTableColumnMissing {
            get {
                return ResourceManager.GetString("MBTTableColumnMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to modify the value of the selected watch variable..
        /// </summary>
        internal static string MBTUnauthorizedChangeValue {
            get {
                return ResourceManager.GetString("MBTUnauthorizedChangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The baseline workset cannot be deleted..
        /// </summary>
        internal static string MBTUnauthorizedDeleteBaselineWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedDeleteBaselineWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to delete the default workset..
        /// </summary>
        internal static string MBTUnauthorizedDeleteDefaultWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedDeleteDefaultWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to delete the selected workset..
        /// </summary>
        internal static string MBTUnauthorizedDeleteWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedDeleteWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The baseline workset cannot be modified..
        /// </summary>
        internal static string MBTUnauthorizedEditBaselineWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedEditBaselineWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to modify the default workset..
        /// </summary>
        internal static string MBTUnauthorizedEditDefaultWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedEditDefaultWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to modify the selected workset..
        /// </summary>
        internal static string MBTUnauthorizedEditWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedEditWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The baseline workset cannot be renamed..
        /// </summary>
        internal static string MBTUnauthorizedRenameBaselineWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedRenameBaselineWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to rename the selected workset..
        /// </summary>
        internal static string MBTUnauthorizedRenameWorkset {
            get {
                return ResourceManager.GetString("MBTUnauthorizedRenameWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data dictionary parameter values of the following watch variables make it unsuitable to plot the values..
        /// </summary>
        internal static string MBTViewDataStreamInvalidWatchIdentifiers {
            get {
                return ResourceManager.GetString("MBTViewDataStreamInvalidWatchIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PTUDLL32 dynamic link library does not support the watch size specified in the data dictionary. Please contact the system adminisrator..
        /// </summary>
        internal static string MBTWatchSizeInvalid {
            get {
                return ResourceManager.GetString("MBTWatchSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified watch variable identifier could not be found in the data dictionary. Please contact the system administrator..
        /// </summary>
        internal static string MBTWatchVariableIDNotFound {
            get {
                return ResourceManager.GetString("MBTWatchVariableIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified watch variable is not defined in the data dictionary..
        /// </summary>
        internal static string MBTWatchVariableNotDefined {
            get {
                return ResourceManager.GetString("MBTWatchVariableNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset &apos;{0}&apos; has been successfully created..
        /// </summary>
        internal static string MBTWorksetCreationSuccess {
            get {
                return ResourceManager.GetString("MBTWorksetCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the selected watch variable(s) will exceed the maximum number that are allowed for this workset..
        /// </summary>
        internal static string MBTWorksetDefineMaxExceeded {
            get {
                return ResourceManager.GetString("MBTWorksetDefineMaxExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available for multiple selections..
        /// </summary>
        internal static string MBTWorksetDefineMultipleSelection {
            get {
                return ResourceManager.GetString("MBTWorksetDefineMultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset &apos;{0}&apos; already exists..
        /// </summary>
        internal static string MBTWorksetExists {
            get {
                return ResourceManager.GetString("MBTWorksetExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worksets contains one or more watch identifiers that are outside the range of the current data dictionary..
        /// </summary>
        internal static string MBTWorksetFileInvalidIdentifiersFound {
            get {
                return ResourceManager.GetString("MBTWorksetFileInvalidIdentifiersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional watch variables have been added to the data dictionary since the worksets were configured..
        /// </summary>
        internal static string MBTWorksetFileNewIdentifiersFound {
            get {
                return ResourceManager.GetString("MBTWorksetFileNewIdentifiersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset file could not be found. Please contact the system administrator..
        /// </summary>
        internal static string MBTWorksetFileNotFound {
            get {
                return ResourceManager.GetString("MBTWorksetFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset file is read-only. Please set the attribute to read/write..
        /// </summary>
        internal static string MBTWorksetFileReadOnly {
            get {
                return ResourceManager.GetString("MBTWorksetFileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset file is corrupt. Please contact the system administrator..
        /// </summary>
        internal static string MBTWorksetFileSerializationError {
            get {
                return ResourceManager.GetString("MBTWorksetFileSerializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset file contains one or more references that do not exist in the data dictionary. Please contact the system administrator..
        /// </summary>
        internal static string MBTWorksetFileUndefinedReferencesFound {
            get {
                return ResourceManager.GetString("MBTWorksetFileUndefinedReferencesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This workset is identical to the workset &apos;{0}&apos; and will not be saved..
        /// </summary>
        internal static string MBTWorksetIdentical {
            get {
                return ResourceManager.GetString("MBTWorksetIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workset of that name already exists, please use another name..
        /// </summary>
        internal static string MBTWorksetNameExists {
            get {
                return ResourceManager.GetString("MBTWorksetNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; workset has been successfully renamed to &apos;{1}&apos;..
        /// </summary>
        internal static string MBTWorksetRenameSuccess {
            get {
                return ResourceManager.GetString("MBTWorksetRenameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All  &apos;{0}&apos; worksets exceed the permitted number of watch variables. Please contact the system administrator..
        /// </summary>
        internal static string MBTWorksetsAllWatchSizeExceeded {
            get {
                return ResourceManager.GetString("MBTWorksetsAllWatchSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following &apos;{0}&apos; workset(s) contain(s) one or more old identifier references that are not defined in the current data dictionary:&quot;.
        /// </summary>
        internal static string MBTWorksetsOldIdentifiersInvalid {
            get {
                return ResourceManager.GetString("MBTWorksetsOldIdentifiersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following &apos;{0}&apos; workset(s) exceed(s) the permitted number of watch variables :.
        /// </summary>
        internal static string MBTWorksetsWatchSizeExceeded {
            get {
                return ResourceManager.GetString("MBTWorksetsWatchSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset &apos;{0}&apos; has been successfully updated..
        /// </summary>
        internal static string MBTWorksetUpdateSuccess {
            get {
                return ResourceManager.GetString("MBTWorksetUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset  exceeds the permitted number of watch variables Please use the Remove button to ensure that the watch variable count is within the limits..
        /// </summary>
        internal static string MBTWorksetWatchSizeExceeded {
            get {
                return ResourceManager.GetString("MBTWorksetWatchSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write the new value to the target hardware..
        /// </summary>
        internal static string MBTWriteFail {
            get {
                return ResourceManager.GetString("MBTWriteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Modify {
            get {
                object obj = ResourceManager.GetObject("Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveDown {
            get {
                object obj = ResourceManager.GetObject("MoveDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveFirst {
            get {
                object obj = ResourceManager.GetObject("MoveFirst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveLast {
            get {
                object obj = ResourceManager.GetObject("MoveLast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveNext {
            get {
                object obj = ResourceManager.GetObject("MoveNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MovePrevious {
            get {
                object obj = ResourceManager.GetObject("MovePrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveUp {
            get {
                object obj = ResourceManager.GetObject("MoveUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultiCursor {
            get {
                object obj = ResourceManager.GetObject("MultiCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        internal static string NameBaselineWorkset {
            get {
                return ResourceManager.GetString("NameBaselineWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Recorder.
        /// </summary>
        internal static string NameConfigureWorksetsChartRecorderMenuOption {
            get {
                return ResourceManager.GetString("NameConfigureWorksetsChartRecorderMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stream.
        /// </summary>
        internal static string NameConfigureWorksetsFaultLogMenuOption {
            get {
                return ResourceManager.GetString("NameConfigureWorksetsFaultLogMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Window.
        /// </summary>
        internal static string NameConfigureWorksetsWatchWindowMenuOption {
            get {
                return ResourceManager.GetString("NameConfigureWorksetsWatchWindowMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [New Workset].
        /// </summary>
        internal static string NameNewWorksetDefault {
            get {
                return ResourceManager.GetString("NameNewWorksetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - [Copy].
        /// </summary>
        internal static string NameWorksetCopy {
            get {
                return ResourceManager.GetString("NameWorksetCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Bombardier\Portable Test Application.
        /// </summary>
        internal static string PathRelativeApplicationData {
            get {
                return ResourceManager.GetString("PathRelativeApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Configuration Files.
        /// </summary>
        internal static string PathRelativeConfigurationFiles {
            get {
                return ResourceManager.GetString("PathRelativeConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Diagnostic Help Files.
        /// </summary>
        internal static string PathRelativeDiagnosticHelpFiles {
            get {
                return ResourceManager.GetString("PathRelativeDiagnosticHelpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Documentation.
        /// </summary>
        internal static string PathRelativeDocumentation {
            get {
                return ResourceManager.GetString("PathRelativeDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Event Logs.
        /// </summary>
        internal static string PathRelativeEventLogs {
            get {
                return ResourceManager.GetString("PathRelativeEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Data Streams.
        /// </summary>
        internal static string PathRelativeFaultLogs {
            get {
                return ResourceManager.GetString("PathRelativeFaultLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Screen Capture Files.
        /// </summary>
        internal static string PathRelativeScreenCaptureFiles {
            get {
                return ResourceManager.GetString("PathRelativeScreenCaptureFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Simulated Data Streams.
        /// </summary>
        internal static string PathRelativeSimulatedFaultLogs {
            get {
                return ResourceManager.GetString("PathRelativeSimulatedFaultLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Watch Files.
        /// </summary>
        internal static string PathRelativeWatchFiles {
            get {
                return ResourceManager.GetString("PathRelativeWatchFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Workset Files.
        /// </summary>
        internal static string PathRelativeWorksetFiles {
            get {
                return ResourceManager.GetString("PathRelativeWorksetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;default&gt;.
        /// </summary>
        internal static string PathUseDefault {
            get {
                return ResourceManager.GetString("PathUseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rename {
            get {
                object obj = ResourceManager.GetObject("Rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Replay {
            get {
                object obj = ResourceManager.GetObject("Replay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fault - Read Timeout..
        /// </summary>
        internal static string SMCommunicationFaultReadTimeout {
            get {
                return ResourceManager.GetString("SMCommunicationFaultReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Plotter Controls..
        /// </summary>
        internal static string SMConfiguringPlotterControls {
            get {
                return ResourceManager.GetString("SMConfiguringPlotterControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Layout..
        /// </summary>
        internal static string SMModifiedPlotLayout {
            get {
                return ResourceManager.GetString("SMModifiedPlotLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused..
        /// </summary>
        internal static string SMPaused {
            get {
                return ResourceManager.GetString("SMPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotting Data..
        /// </summary>
        internal static string SMPlottingData {
            get {
                return ResourceManager.GetString("SMPlottingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current name is in use, please use another name..
        /// </summary>
        internal static string SMWorksetNameExists {
            get {
                return ResourceManager.GetString("SMWorksetNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset must be given a name before it can be saved..
        /// </summary>
        internal static string SMWorksetNameNotDefined {
            get {
                return ResourceManager.GetString("SMWorksetNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workset must contain at least one watch variable before it can be saved..
        /// </summary>
        internal static string SMWorksetWatchCountTooSmall {
            get {
                return ResourceManager.GetString("SMWorksetWatchCountTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Copy].
        /// </summary>
        internal static string TextCopy {
            get {
                return ResourceManager.GetString("TextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string TextNotAvailable {
            get {
                return ResourceManager.GetString("TextNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string TextUnavailable {
            get {
                return ResourceManager.GetString("TextUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        internal static string TitleReplay {
            get {
                return ResourceManager.GetString("TitleReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trip {
            get {
                object obj = ResourceManager.GetObject("Trip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YTPlot {
            get {
                object obj = ResourceManager.GetObject("YTPlot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
