//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the watch variable identifier associated with channel {0} of the chart recorder..
        /// </summary>
        internal static string EMGetChartRecorderWatchIDFailed {
            get {
                return ResourceManager.GetString("EMGetChartRecorderWatchIDFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write the new value to the target hardware..
        /// </summary>
        internal static string EMSendVariableFailed {
            get {
                return ResourceManager.GetString("EMSendVariableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the watch variable identifier associated with channel {0} of the chart recorder..
        /// </summary>
        internal static string EMSetChartRecorderWatchIDFailed {
            get {
                return ResourceManager.GetString("EMSetChartRecorderWatchIDFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to map the watch identifiers to the watch elements..
        /// </summary>
        internal static string EMSetWatchElementsFailed {
            get {
                return ResourceManager.GetString("EMSetWatchElementsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the watch elements from the target hardware..
        /// </summary>
        internal static string EMUpdateWatchElementsFailed {
            get {
                return ResourceManager.GetString("EMUpdateWatchElementsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the integrity check on the workset, please contact the system administrator..
        /// </summary>
        internal static string EMWorksetIntegrityCheckFailed {
            get {
                return ResourceManager.GetString("EMWorksetIntegrityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Watch Files.
        /// </summary>
        internal static string FileDialogOpenFilterRecordedWatchFile {
            get {
                return ResourceManager.GetString("FileDialogOpenFilterRecordedWatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated Data Stream Files.
        /// </summary>
        internal static string FileDialogOpenFilterSimulatedFaultLog {
            get {
                return ResourceManager.GetString("FileDialogOpenFilterSimulatedFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Recorded Watch File.
        /// </summary>
        internal static string FileDialogOpenTitleRecordedWatchFile {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleRecordedWatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Simulated Data Stream.
        /// </summary>
        internal static string FileDialogOpenTitleSimulatedFaultLog {
            get {
                return ResourceManager.GetString("FileDialogOpenTitleSimulatedFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileInformation {
            get {
                object obj = ResourceManager.GetObject("FileInformation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cont..
        /// </summary>
        internal static string FunctionKeyTextContinue {
            get {
                return ResourceManager.GetString("FunctionKeyTextContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string FunctionKeyTextEdit {
            get {
                return ResourceManager.GetString("FunctionKeyTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string FunctionKeyTextInfo {
            get {
                return ResourceManager.GetString("FunctionKeyTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string FunctionKeyTextPause {
            get {
                return ResourceManager.GetString("FunctionKeyTextPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec..
        /// </summary>
        internal static string FunctionKeyTextRecord {
            get {
                return ResourceManager.GetString("FunctionKeyTextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FunctionKeyTextSave {
            get {
                return ResourceManager.GetString("FunctionKeyTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string FunctionKeyTextStop {
            get {
                return ResourceManager.GetString("FunctionKeyTextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Continue].
        /// </summary>
        internal static string FunctionKeyToolTipContinue {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Modify Current Workset].
        /// </summary>
        internal static string FunctionKeyToolTipEdit {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Show Header Information].
        /// </summary>
        internal static string FunctionKeyToolTipInfo {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Pause].
        /// </summary>
        internal static string FunctionKeyToolTipPause {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Record].
        /// </summary>
        internal static string FunctionKeyToolTipRecord {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Save].
        /// </summary>
        internal static string FunctionKeyToolTipSave {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Stop Recording] .
        /// </summary>
        internal static string FunctionKeyToolTipStop {
            get {
                return ResourceManager.GetString("FunctionKeyToolTipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string InformationLegendDate {
            get {
                return ResourceManager.GetString("InformationLegendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string InformationLegendDuration {
            get {
                return ResourceManager.GetString("InformationLegendDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec. Start:.
        /// </summary>
        internal static string InformationLegendRecordingStartTime {
            get {
                return ResourceManager.GetString("InformationLegendRecordingStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Time:.
        /// </summary>
        internal static string InformationLegendTime {
            get {
                return ResourceManager.GetString("InformationLegendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string LegendAvailable {
            get {
                return ResourceManager.GetString("LegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string LegendCount {
            get {
                return ResourceManager.GetString("LegendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Hex).
        /// </summary>
        internal static string LegendFormatHex {
            get {
                return ResourceManager.GetString("LegendFormatHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string LegendOf {
            get {
                return ResourceManager.GetString("LegendOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording:.
        /// </summary>
        internal static string LegendRecording {
            get {
                return ResourceManager.GetString("LegendRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        internal static string LegendTotalCount {
            get {
                return ResourceManager.GetString("LegendTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wor&amp;kset:.
        /// </summary>
        internal static string LegendWorkset {
            get {
                return ResourceManager.GetString("LegendWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MBCaptionError {
            get {
                return ResourceManager.GetString("MBCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MBCaptionInformation {
            get {
                return ResourceManager.GetString("MBCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MBCaptionWarning {
            get {
                return ResourceManager.GetString("MBCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or both of the chart recorder Y axis limits for this watch variable contain(s) invalid data. The upper and lower limits wil be set to their default values..
        /// </summary>
        internal static string MBTChartScaleLimitsInvalid {
            get {
                return ResourceManager.GetString("MBTChartScaleLimitsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry error - The lower limit must be less than or equal to the upper limit..
        /// </summary>
        internal static string MBTChartScaleLowerLimitInvalid {
            get {
                return ResourceManager.GetString("MBTChartScaleLowerLimitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry error - The upper limit must be greater than or equal to the lower limit..
        /// </summary>
        internal static string MBTChartScaleUpperLimitInvalid {
            get {
                return ResourceManager.GetString("MBTChartScaleUpperLimitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry error - The specified value did not represent a valid 32 bit decimal value..
        /// </summary>
        internal static string MBTDataEntryDecimalInvalid {
            get {
                return ResourceManager.GetString("MBTDataEntryDecimalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry error - The specified value did not represent a valid 32 bit hexadecimal value..
        /// </summary>
        internal static string MBTDataEntryHexInvalid {
            get {
                return ResourceManager.GetString("MBTDataEntryHexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to modify the current workset..
        /// </summary>
        internal static string MBTInsufficientPrivilegesEdit {
            get {
                return ResourceManager.GetString("MBTInsufficientPrivilegesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the baseline workset &apos;{0}&apos;..
        /// </summary>
        internal static string MBTLoadingBaselineWorkset {
            get {
                return ResourceManager.GetString("MBTLoadingBaselineWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This log file type is not supported..
        /// </summary>
        internal static string MBTLogFileTypeNotSupported {
            get {
                return ResourceManager.GetString("MBTLogFileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to re-configure the chart recorder channels..
        /// </summary>
        internal static string MBTModifyChannelsFailed {
            get {
                return ResourceManager.GetString("MBTModifyChannelsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart recorder has been successfully re-configured..
        /// </summary>
        internal static string MBTModifyChartRecorderConfigurationSuccess {
            get {
                return ResourceManager.GetString("MBTModifyChartRecorderConfigurationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify the upper and lower limits of the chart recorder channel..
        /// </summary>
        internal static string MBTModifyLimitFailed {
            get {
                return ResourceManager.GetString("MBTModifyLimitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to modify the chart recorder channel configuration to the selected settings ?.
        /// </summary>
        internal static string MBTQueryModifyChartRecorderChannels {
            get {
                return ResourceManager.GetString("MBTQueryModifyChartRecorderChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid worksets were found..
        /// </summary>
        internal static string MBTValidWorksetNotFound {
            get {
                return ResourceManager.GetString("MBTValidWorksetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected watch variable does not exist..
        /// </summary>
        internal static string MBTWatchVariableNotFound {
            get {
                return ResourceManager.GetString("MBTWatchVariableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Modify {
            get {
                object obj = ResourceManager.GetObject("Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        internal static string NameBaselineWorkset {
            get {
                return ResourceManager.GetString("NameBaselineWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Record {
            get {
                object obj = ResourceManager.GetObject("Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecordStop {
            get {
                object obj = ResourceManager.GetObject("RecordStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fault - Port Locked..
        /// </summary>
        internal static string SMCommunicationFaultPortLocked {
            get {
                return ResourceManager.GetString("SMCommunicationFaultPortLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fault - Read Timeout..
        /// </summary>
        internal static string SMCommunicationFaultReadTimeout {
            get {
                return ResourceManager.GetString("SMCommunicationFaultReadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused..
        /// </summary>
        internal static string SMFunctionKeyPause {
            get {
                return ResourceManager.GetString("SMFunctionKeyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure - Chart Recorder.
        /// </summary>
        internal static string TitleConfigureChartRecorder {
            get {
                return ResourceManager.GetString("TitleConfigureChartRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy - Chart Recorder Workset.
        /// </summary>
        internal static string TitleCopyChartRecorderWorkset {
            get {
                return ResourceManager.GetString("TitleCopyChartRecorderWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New - Chart Recorder Workset.
        /// </summary>
        internal static string TitleCreateChartRecorderWorkset {
            get {
                return ResourceManager.GetString("TitleCreateChartRecorderWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify - Chart Recorder Workset.
        /// </summary>
        internal static string TitleEditChartRecorderWorkset {
            get {
                return ResourceManager.GetString("TitleEditChartRecorderWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Simulated Data Stream: {0}.
        /// </summary>
        internal static string TitleOpenSimulatedFaultLog {
            get {
                return ResourceManager.GetString("TitleOpenSimulatedFaultLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Watch File : {0}.
        /// </summary>
        internal static string TitleOpenWatchFile {
            get {
                return ResourceManager.GetString("TitleOpenWatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename - Chart Recorder Workset.
        /// </summary>
        internal static string TitleRenameChartRecorderWorkset {
            get {
                return ResourceManager.GetString("TitleRenameChartRecorderWorkset", resourceCulture);
            }
        }
    }
}
